#!/usr/bin/env python3
"""
Self Improver — Generated by Agent Ontology Instantiation Engine (LangGraph backend)
Spec: Reads an agent spec YAML, analyzes it for structural weaknesses (lint warnings, missing patterns, complexity issues), proposes mutations, validates the result, and outputs an improved spec.
"""

import json
import operator
import os
import sys
import time
from datetime import datetime
from typing import Any, TypedDict, Annotated

from langgraph.graph import StateGraph, END

# ═══════════════════════════════════════════════════════════
# Trace Log
# ═══════════════════════════════════════════════════════════

TRACE = []

def trace_call(agent_label, model, system_prompt, user_message, response, duration_ms):
    entry = {
        "timestamp": datetime.now().isoformat(),
        "agent": agent_label,
        "model": model,
        "system_prompt": system_prompt,
        "user_message": user_message,
        "response": response,
        "duration_ms": duration_ms,
    }
    TRACE.append(entry)
    print(f"    [{agent_label}] ({model}, {duration_ms}ms)")
    print(f"      IN:  {user_message[:300]}")
    print(f"      OUT: {response[:300]}")


def dump_trace(path="trace.json", iterations=0, clean_exit=True):
    total_ms = sum(e["duration_ms"] for e in TRACE)
    agents_used = list(set(e["agent"] for e in TRACE))
    schema_ok = 0
    for e in TRACE:
        try:
            r = e["response"].strip()
            if r.startswith("```"): r = "\n".join(r.split("\n")[1:-1])
            json.loads(r if r.startswith("{") else r[r.find("{"):r.rfind("}")+1])
            schema_ok += 1
        except (json.JSONDecodeError, ValueError):
            pass
    est_input_tokens = sum(len(e.get("user_message",""))//4 for e in TRACE)
    est_output_tokens = sum(len(e.get("response",""))//4 for e in TRACE)
    metrics = {
        "total_llm_calls": len(TRACE),
        "total_duration_ms": total_ms,
        "avg_call_ms": total_ms // max(len(TRACE), 1),
        "iterations": iterations,
        "clean_exit": clean_exit,
        "agents_used": agents_used,
        "schema_compliance": f"{schema_ok}/{len(TRACE)}",
        "est_input_tokens": est_input_tokens,
        "est_output_tokens": est_output_tokens,
    }
    output = {"metrics": metrics, "trace": TRACE}
    with open(path, "w") as f:
        json.dump(output, f, indent=2)
    print(f"\nTrace written to {path} ({len(TRACE)} calls, {total_ms}ms total)")
    print(f"  Schema compliance: {schema_ok}/{len(TRACE)}, est tokens: ~{est_input_tokens}in/~{est_output_tokens}out")
    return metrics

# ═══════════════════════════════════════════════════════════
# LLM Call Infrastructure
# ═══════════════════════════════════════════════════════════

_MODEL_OVERRIDE = os.environ.get("AGENT_ONTOLOGY_MODEL", "")
_OPENROUTER_API_KEY = os.environ.get("OPENROUTER_API_KEY", "")


def _openrouter_model_id(model):
    """Map spec model names to OpenRouter model IDs (provider/model format)."""
    if "/" in model:
        return model
    if model.startswith("gemini"):
        return f"google/{model}"
    if model.startswith("claude") or model.startswith("anthropic"):
        return f"anthropic/{model}"
    if model.startswith("gpt") or model.startswith("o1") or model.startswith("o3"):
        return f"openai/{model}"
    return model


def _get_chat_model(model, temperature=0.7, max_tokens=4096):
    """Get a LangChain ChatModel instance for the given model name."""
    if _OPENROUTER_API_KEY:
        from langchain_openai import ChatOpenAI
        return ChatOpenAI(
            model=_openrouter_model_id(model),
            temperature=temperature,
            max_tokens=max_tokens,
            base_url="https://openrouter.ai/api/v1",
            api_key=_OPENROUTER_API_KEY,
        )
    if model.startswith("gemini"):
        from langchain_google_genai import ChatGoogleGenerativeAI
        return ChatGoogleGenerativeAI(model=model, temperature=temperature,
                                      max_output_tokens=max_tokens,
                                      google_api_key=os.environ.get("GEMINI_API_KEY", ""))
    elif model.startswith("claude") or model.startswith("anthropic"):
        from langchain_anthropic import ChatAnthropic
        return ChatAnthropic(model=model, temperature=temperature, max_tokens=max_tokens)
    else:
        from langchain_openai import ChatOpenAI
        return ChatOpenAI(model=model, temperature=temperature, max_tokens=max_tokens)


def call_llm(model, system_prompt, user_message, temperature=0.7, max_tokens=4096, retries=3):
    if _MODEL_OVERRIDE:
        model = _MODEL_OVERRIDE
    from langchain_core.messages import SystemMessage, HumanMessage
    for attempt in range(retries):
        try:
            chat = _get_chat_model(model, temperature, max_tokens)
            messages = [SystemMessage(content=system_prompt), HumanMessage(content=user_message)]
            response = chat.invoke(messages)
            content = response.content
            # LangChain may return content as a list of blocks (e.g. Gemini)
            if isinstance(content, list):
                content = " ".join(b.get("text", str(b)) if isinstance(b, dict) else str(b) for b in content)
            return content
        except Exception as e:
            if attempt < retries - 1:
                wait = 2 ** attempt
                print(f"    [RETRY] {type(e).__name__}: {e} — retrying in {wait}s (attempt {attempt+1}/{retries})")
                import time as _time; _time.sleep(wait)
            else:
                print(f"    [FAIL] {type(e).__name__}: {e} after {retries} attempts")
                return json.dumps({"stub": True, "model": model, "error": str(e)})

# ═══════════════════════════════════════════════════════════
# Schema Registry
# ═══════════════════════════════════════════════════════════

SCHEMAS = {
    "SpecInput": {
        "description": """The spec to improve""",
        "fields": [{"name": "spec_yaml", "type": "string"}, {"name": "max_rounds", "type": "integer"}],
    },
    "AnalysisResult": {
        "description": """Results of analyzing a spec""",
        "fields": [{"name": "lint_warnings", "type": "list<object>"}, {"name": "verify_issues", "type": "list<object>"}, {"name": "detected_patterns", "type": "list<string>"}, {"name": "entity_count", "type": "integer"}, {"name": "process_count", "type": "integer"}, {"name": "edge_count", "type": "integer"}, {"name": "schema_count", "type": "integer"}],
    },
    "AnalystInput": {
        "description": """Input to the architecture analyst""",
        "fields": [{"name": "spec_yaml", "type": "string"}, {"name": "spec_name", "type": "string"}, {"name": "lint_warnings", "type": "list<object>"}, {"name": "verify_issues", "type": "list<object>"}, {"name": "detected_patterns", "type": "list<string>"}, {"name": "entity_count", "type": "integer"}, {"name": "process_count", "type": "integer"}, {"name": "improvements_made", "type": "list<object>"}],
    },
    "AnalystOutput": {
        "description": """Diagnosis and proposed improvement""",
        "fields": [{"name": "diagnosis", "type": "string"}, {"name": "improvement_type", "type": "string"}, {"name": "improvement_details", "type": "string"}, {"name": "expected_benefit", "type": "string"}, {"name": "risk", "type": "string"}],
    },
    "MutatorInput": {
        "description": """Input to the spec mutator""",
        "fields": [{"name": "current_spec_yaml", "type": "string"}, {"name": "improvement_type", "type": "string"}, {"name": "improvement_details", "type": "string"}, {"name": "diagnosis", "type": "string"}],
    },
    "MutatorOutput": {
        "description": """The mutated spec""",
        "fields": [{"name": "mutated_spec_yaml", "type": "string"}, {"name": "changes_summary", "type": "string"}, {"name": "processes_added", "type": "list<string>"}, {"name": "processes_removed", "type": "list<string>"}],
    },
    "ValidationResult": {
        "description": """Validation results for the mutated spec""",
        "fields": [{"name": "mutation_valid", "type": "boolean"}, {"name": "validation_errors", "type": "list<string>"}],
    },
    "EvaluatorInput": {
        "description": """Input to the improvement evaluator""",
        "fields": [{"name": "diagnosis", "type": "string"}, {"name": "improvement_type", "type": "string"}, {"name": "changes_summary", "type": "string"}, {"name": "lint_warnings", "type": "list<object>"}, {"name": "new_lint_warnings", "type": "list<object>"}, {"name": "verify_issues", "type": "list<object>"}, {"name": "new_verify_issues", "type": "list<object>"}],
    },
    "EvaluatorOutput": {
        "description": """Evaluation of the improvement""",
        "fields": [{"name": "improved", "type": "boolean"}, {"name": "score_delta", "type": "integer"}, {"name": "warnings_fixed", "type": "integer"}, {"name": "warnings_introduced", "type": "integer"}, {"name": "reasoning", "type": "string"}],
    },
    "FinalResult": {
        "description": """The improved spec with summary""",
        "fields": [{"name": "final_spec_yaml", "type": "string"}, {"name": "total_improvements", "type": "integer"}, {"name": "improvements_made", "type": "list<object>"}],
    },
}


def validate_output(data, schema_name):
    schema = SCHEMAS.get(schema_name)
    if not schema or "raw" in data:
        return []
    issues = []
    for field in schema["fields"]:
        fname = field["name"]
        ftype = field["type"]
        if fname not in data:
            issues.append(f"Missing field '{fname}' ({ftype})")
            continue
        val = data[fname]
        if ftype == "string" and not isinstance(val, str):
            issues.append(f"Field '{fname}' expected string, got {type(val).__name__}")
        elif ftype == "integer" and not isinstance(val, (int, float)):
            issues.append(f"Field '{fname}' expected integer, got {type(val).__name__}")
        elif ftype.startswith("list") and not isinstance(val, list):
            issues.append(f"Field '{fname}' expected list, got {type(val).__name__}")
        elif ftype.startswith("enum["):
            allowed = [v.strip() for v in ftype[5:-1].split(",")]
            if val not in allowed:
                issues.append(f"Field '{fname}' value '{val}' not in {allowed}")
    if issues:
        print(f"    [SCHEMA] {schema_name}: {len(issues)} issue(s): {issues[0]}")
    return issues


def build_input(state, schema_name):
    """Build an input dict for an agent call using schema field names."""
    schema = SCHEMAS.get(schema_name)
    if not schema:
        return dict(state)
    result = {}
    for field in schema["fields"]:
        fname = field["name"]
        if fname in state:
            result[fname] = state[fname]
        else:
            for _k, _v in state.items():
                if isinstance(_v, dict) and fname in _v:
                    result[fname] = _v[fname]
                    break
    return result


def output_instruction(schema_name):
    schema = SCHEMAS.get(schema_name)
    if not schema:
        return ""
    fields = ", ".join(f'"{f["name"]}": <{f["type"]}>' for f in schema["fields"])
    return f"\n\nRespond with ONLY valid JSON matching this schema: {{{fields}}}"


def parse_response(response, schema_name):
    import re as _re
    text = response.strip()
    if text.startswith("```"):
        lines = text.split("\n")
        lines = lines[1:]
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        text = "\n".join(lines)
    try:
        parsed = json.loads(text)
        if isinstance(parsed, dict):
            return parsed
        return {"value": parsed}
    except json.JSONDecodeError:
        pass
    start = text.find("{")
    end = text.rfind("}") + 1
    if start >= 0 and end > start:
        candidate = text[start:end]
        try:
            return json.loads(candidate)
        except json.JSONDecodeError:
            pass
        fixed = _re.sub(r",\s*}", "}", candidate)
        fixed = _re.sub(r",\s*]", "]", fixed)
        try:
            return json.loads(fixed)
        except json.JSONDecodeError:
            pass
        depth = 0
        for i, ch in enumerate(text[start:], start):
            if ch == "{": depth += 1
            elif ch == "}": depth -= 1
            if depth == 0:
                try:
                    return json.loads(text[start:i+1])
                except json.JSONDecodeError:
                    break
    return {"raw": response}

# ═══════════════════════════════════════════════════════════
# State TypedDict
# ═══════════════════════════════════════════════════════════

class AgentState(TypedDict, total=False):
    """Typed state for Self Improver"""
    _canned_responses: list
    _done: bool
    _iteration: int
    _schema_violations: Annotated[int, operator.add]
    _skip_to_finalize: Any
    changes_summary: str
    current_spec_yaml: str
    detected_patterns: list
    diagnose_result: Any
    diagnosis: str
    edge_count: int
    entity_count: int
    evaluate_result: Any
    expected_benefit: str
    final_spec_yaml: str
    improved: bool
    improvement_details: str
    improvement_round: Any
    improvement_type: str
    improvements_made: list
    lint_warnings: list
    max_rounds: int
    mutate_spec_result: Any
    mutated_spec_yaml: str
    mutation_valid: bool
    new_edge_count: Any
    new_entity_count: Any
    new_lint_warnings: list
    new_process_count: Any
    new_verify_issues: list
    original_spec_yaml: Any
    process_count: int
    processes_added: list
    processes_removed: list
    raw: Any
    reasoning: str
    risk: str
    schema_count: int
    score_delta: int
    spec_name: str
    spec_yaml: str
    total_improvements: int
    validation_errors: list
    verify_issues: list
    warnings_fixed: int
    warnings_introduced: int


# ═══════════════════════════════════════════════════════════
# Agent Wrappers
# ═══════════════════════════════════════════════════════════

def invoke_analyst(user_message, output_schema=None):
    """Architecture Analyst"""
    system = """You are an expert AI agent architect. Given a YAML agent spec and analysis results
(lint warnings, verification issues, detected patterns, complexity metrics), identify
the most impactful improvement to make. Consider:
- Fixing lint warnings (dead stores, schema mismatches, unbounded loops)
- Adding missing patterns (e.g., adding a critique step, error handling)
- Simplifying over-complex structures
- Improving data flow (adding missing read/write edges)

Output JSON with:
- "diagnosis" (string): What is the primary weakness
- "improvement_type" (string): One of: add_review_step, add_store, change_gate_condition,
  modify_prompt, swap_pattern, insert_pattern, remove_process, change_model
- "improvement_details" (string): Specific description of the change
- "expected_benefit" (string): Why this improves the agent
- "risk" (string): What could go wrong
"""
    if output_schema:
        system += output_instruction(output_schema)
    t0 = time.time()
    result = call_llm(
        model="gemini-3-flash-preview",
        system_prompt=system,
        user_message=user_message,
        temperature=0.7,
        max_tokens=4096,
    )
    trace_call("Architecture Analyst", "gemini-3-flash-preview", system, user_message, result, int((time.time()-t0)*1000))
    return result


def invoke_mutator(user_message, output_schema=None):
    """Spec Mutator"""
    system = """You are a precise YAML spec editor. Given an agent spec (as YAML text), an improvement
type, and improvement details, apply the mutation to produce a modified spec.

Rules:
- Preserve the YAML structure (entities, processes, edges, schemas sections)
- Every new entity/process must be connected via edges
- Every schema referenced must be defined
- Gate conditions must reference fields that exist in upstream schemas
- Do NOT remove the entry_point process
- Do NOT break existing flow chains — add to them

Output JSON with:
- "mutated_spec_yaml" (string): The complete modified YAML spec
- "changes_summary" (string): What was changed and why
- "processes_added" (list of strings): IDs of any new processes
- "processes_removed" (list of strings): IDs of any removed processes
"""
    if output_schema:
        system += output_instruction(output_schema)
    t0 = time.time()
    result = call_llm(
        model="gemini-3-flash-preview",
        system_prompt=system,
        user_message=user_message,
        temperature=0.7,
        max_tokens=4096,
    )
    trace_call("Spec Mutator", "gemini-3-flash-preview", system, user_message, result, int((time.time()-t0)*1000))
    return result


def invoke_evaluator(user_message, output_schema=None):
    """Improvement Evaluator"""
    system = """You are a quality evaluator for agent architecture changes. Compare the original
spec analysis with the mutated spec analysis and determine if the mutation improved
the architecture. Consider:
- Were lint warnings reduced?
- Were verification issues fixed?
- Did complexity change appropriately?
- Were any new issues introduced?

Output JSON with:
- "improved" (boolean): Is the mutation an improvement overall?
- "score_delta" (integer): Change in quality score (-10 to +10)
- "warnings_fixed" (integer): Number of lint warnings eliminated
- "warnings_introduced" (integer): Number of new warnings
- "reasoning" (string): Explanation of your assessment
"""
    if output_schema:
        system += output_instruction(output_schema)
    t0 = time.time()
    result = call_llm(
        model="gemini-3-flash-preview",
        system_prompt=system,
        user_message=user_message,
        temperature=0.7,
        max_tokens=4096,
    )
    trace_call("Improvement Evaluator", "gemini-3-flash-preview", system, user_message, result, int((time.time()-t0)*1000))
    return result



# ═══════════════════════════════════════════════════════════
# Node Functions
# ═══════════════════════════════════════════════════════════

def node_receive_spec(state: AgentState) -> dict:
    """
    Receive Spec
    Load the target spec and initialize improvement state
    """
    print(f"  → Receive Spec")
    updates = {}

    # Logic from spec
    updates["improvement_round"] = 0
    updates["max_rounds"] = state.get("max_rounds", 2)
    updates["improvements_made"] = []
    updates["original_spec_yaml"] = state.get("spec_yaml", "")
    updates["current_spec_yaml"] = state.get("original_spec_yaml", "")
    print(f"    Loaded spec ({len(state.get('current_spec_yaml', ""))} chars)")
    if updates.get("_done") or state.get("_done"):
        return updates

    return updates


def node_analyze_spec(state: AgentState) -> dict:
    """
    Analyze Spec
    Run lint, verify, and pattern detection on the current spec
    """
    print(f"  → Analyze Spec")
    updates = {}

    # Logic from spec
    import yaml as _yaml
    import tempfile, os
    spec_yaml = state.get("current_spec_yaml", "")
    # Write spec to temp file for analysis tools
    tmp = tempfile.NamedTemporaryFile(mode='w', suffix='.yaml', delete=False)
    tmp.write(spec_yaml)
    tmp.close()
    tmp_path = tmp.name
    try:
        # Parse the spec
        spec = _yaml.safe_load(spec_yaml)
        updates["spec_name"] = spec.get("name", "unknown")
        # Run lint
        try:
            from agent_ontology.lint import lint_spec
            lint_results = lint_spec(spec)
            updates["lint_warnings"] = [{"rule": r.code, "severity": r.severity, "message": r.message} for r in lint_results]
            print(f"    Lint: {len(lint_results)} warnings")
        except Exception as e:
            updates["lint_warnings"] = []
            print(f"    Lint failed: {e}")
        # Run verify
        try:
            from agent_ontology.verify import verify_spec
            passes, failures = verify_spec(spec, spec_path=tmp_path)
            updates["verify_issues"] = [{"check": f, "status": "fail"} for f in failures]
            print(f"    Verify: {len(failures)} issues, {len(passes)} passed")
        except Exception as e:
            updates["verify_issues"] = []
            print(f"    Verify failed: {e}")
        # Detect patterns
        try:
            from agent_ontology.patterns import detect_patterns
            patterns = detect_patterns(spec)
            updates["detected_patterns"] = list(patterns.keys()) if isinstance(patterns, dict) else patterns
            print(f"    Patterns: {state.get('detected_patterns', "")}")
        except Exception as e:
            updates["detected_patterns"] = []
            print(f"    Pattern detection failed: {e}")
        # Count entities/processes/edges
        updates["entity_count"] = len(spec.get("entities", []))
        updates["process_count"] = len(spec.get("processes", []))
        updates["edge_count"] = len(spec.get("edges", []))
        updates["schema_count"] = len(spec.get("schemas", []))
    finally:
        os.unlink(tmp_path)
    if updates.get("_done") or state.get("_done"):
        return updates

    return updates


def node_diagnose(state: AgentState) -> dict:
    """
    Diagnose Weaknesses
    Use the analyst agent to identify the most impactful improvement
    """
    print(f"  → Diagnose Weaknesses")
    updates = {}

    # Logic from spec
    round_num = state.get("improvement_round", 0)
    print(f"    Round {round_num + 1}: Diagnosing weaknesses...")
    lint_count = len(state.get("lint_warnings", []))
    verify_issues = len([v for v in state.get("verify_issues", []) if v.get("status") != "pass"])
    print(f"    {lint_count} lint warnings, {verify_issues} verify issues")
    if updates.get("_done") or state.get("_done"):
        return updates

    # Flatten nested dicts
    _combined = dict(state)
    _combined.update(updates)
    for _nested_val in list(_combined.values()):
        if isinstance(_nested_val, dict):
            for _nk, _nv in _nested_val.items():
                if _nk not in _combined:
                    updates[_nk] = _nv

    # Invoke: Diagnose weaknesses
    _cur = dict(state)
    _cur.update(updates)
    analyst_input = build_input(_cur, "AnalystInput")
    analyst_msg = json.dumps(analyst_input, default=str)
    analyst_raw = invoke_analyst(analyst_msg, output_schema="AnalystOutput")
    analyst_result = parse_response(analyst_raw, "AnalystOutput")
    updates["_schema_violations"] = len(validate_output(analyst_result, "AnalystOutput"))
    updates.update(analyst_result)
    updates["analyst_output"] = analyst_result
    updates["diagnose_result"] = analyst_result
    print(f"    ← Architecture Analyst: {analyst_result}")

    return updates


def node_mutate_spec(state: AgentState) -> dict:
    """
    Mutate Spec
    Apply the proposed mutation to the spec
    """
    print(f"  → Mutate Spec")
    updates = {}

    # Logic from spec
    improvement = state.get("improvement_type", "unknown")
    details = state.get("improvement_details", "")
    print(f"    Applying mutation: {improvement}")
    print(f"    Details: {details[:100]}")
    if updates.get("_done") or state.get("_done"):
        return updates

    # Flatten nested dicts
    _combined = dict(state)
    _combined.update(updates)
    for _nested_val in list(_combined.values()):
        if isinstance(_nested_val, dict):
            for _nk, _nv in _nested_val.items():
                if _nk not in _combined:
                    updates[_nk] = _nv

    # Invoke: Apply mutation
    _cur = dict(state)
    _cur.update(updates)
    mutator_input = build_input(_cur, "MutatorInput")
    mutator_msg = json.dumps(mutator_input, default=str)
    mutator_raw = invoke_mutator(mutator_msg, output_schema="MutatorOutput")
    mutator_result = parse_response(mutator_raw, "MutatorOutput")
    updates["_schema_violations"] = len(validate_output(mutator_result, "MutatorOutput"))
    updates.update(mutator_result)
    updates["mutator_output"] = mutator_result
    updates["mutate_spec_result"] = mutator_result
    print(f"    ← Spec Mutator: {mutator_result}")

    return updates


def node_extract_mutated_yaml(state: AgentState) -> dict:
    """
    Extract Mutated YAML
    Extract the mutated YAML from the mutator response, handling JSON parsing edge cases
    """
    print(f"  → Extract Mutated YAML")
    updates = {}

    # Logic from spec
    import re as _re, json as _json
    mutated = state.get("mutated_spec_yaml", "")
    if not mutated.strip():
        raw = state.get("raw", "")
        if raw:
            # Try full JSON parse of the raw response
            try:
                parsed = _json.loads(raw)
                if isinstance(parsed, dict) and parsed.get("mutated_spec_yaml"):
                    mutated = parsed["mutated_spec_yaml"]
                    updates["mutated_spec_yaml"] = mutated
                    print(f"    Parsed mutated YAML from JSON ({len(mutated)} chars)")
            except _json.JSONDecodeError:
                pass
        if not mutated.strip() and raw:
            # Try regex extraction from JSON-escaped string
            m = _re.search(r'"mutated_spec_yaml"\s*:\s*"', raw)
            if m:
                start = m.end()
                # Walk forward to find unescaped closing quote
                i = start
                while i < len(raw):
                    if raw[i] == '\\' and i + 1 < len(raw):
                        i += 2
                        continue
                    if raw[i] == '"':
                        break
                    i += 1
                yaml_escaped = raw[start:i]
                mutated = yaml_escaped.replace('\\n', '\n').replace('\\t', '\t').replace('\\"', '"').replace('\\\\', '\\')
                updates["mutated_spec_yaml"] = mutated
                print(f"    Extracted YAML via regex ({len(mutated)} chars)")
        if not mutated.strip():
            print(f"    Could not extract mutated YAML (raw len={len(state.get('raw', ''))})")
    else:
        print(f"    Mutated YAML already present ({len(mutated)} chars)")
    if updates.get("_done") or state.get("_done"):
        return updates

    return updates


def node_validate_mutation(state: AgentState) -> dict:
    """
    Validate Mutation
    Check if the mutated spec is valid YAML and passes validation
    """
    print(f"  → Validate Mutation")
    updates = {}

    # Logic from spec
    import yaml as _yaml
    import tempfile, os
    mutated_yaml = state.get("mutated_spec_yaml", "")
    updates["mutation_valid"] = False
    updates["validation_errors"] = []
    if not mutated_yaml.strip():
        updates["validation_errors"] = ["Empty spec"]
        print("    Mutation produced empty spec")
    else:
        try:
            spec = _yaml.safe_load(mutated_yaml)
            if not isinstance(spec, dict):
                updates["validation_errors"] = ["Not a valid YAML dict"]
                print("    Invalid YAML structure")
            elif "entities" not in spec or "processes" not in spec:
                updates["validation_errors"] = ["Missing entities or processes"]
                print("    Missing required sections")
            else:
                # Write to temp and validate
                tmp = tempfile.NamedTemporaryFile(mode='w', suffix='.yaml', delete=False)
                tmp.write(mutated_yaml)
                tmp.close()
                try:
                    from agent_ontology.validate import validate_spec, load_yaml
                    ontology_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'agent_ontology', 'ONTOLOGY.yaml')
                    if not os.path.exists(ontology_path):
                        import agent_ontology
                        ontology_path = os.path.join(os.path.dirname(agent_ontology.__file__), 'ONTOLOGY.yaml')
                    ontology = load_yaml(ontology_path)
                    errors, warnings = validate_spec(spec, ontology, tmp.name)
                    updates["validation_errors"] = errors
                    if errors:
                        print(f"    Validation: {len(errors)} errors")
                    else:
                        updates["mutation_valid"] = True
                        print("    Validation: PASS")
                except Exception as e:
                    updates["validation_errors"] = [str(e)]
                    print(f"    Validation failed: {e}")
                finally:
                    os.unlink(tmp.name)
        except _yaml.YAMLError as e:
            updates["validation_errors"] = [f"YAML parse error: {e}"]
            print(f"    YAML parse error: {e}")
    if updates.get("_done") or state.get("_done"):
        return updates

    return updates


def node_handle_invalid(state: AgentState) -> dict:
    """
    Handle Invalid Mutation
    Record the failure and decide whether to retry or give up
    """
    print(f"  → Handle Invalid Mutation")
    updates = {}

    # Logic from spec
    errors = state.get("validation_errors", [])
    print(f"    Mutation invalid: {errors[:2]}")
    # Skip this improvement, move to finalize
    updates["improvement_round"] = state.get("max_rounds", 2)
    updates["_skip_to_finalize"] = True
    if updates.get("_done") or state.get("_done"):
        return updates

    return updates


def node_reanalyze(state: AgentState) -> dict:
    """
    Re-analyze Mutated Spec
    Run analysis on the mutated spec to compare with original
    """
    print(f"  → Re-analyze Mutated Spec")
    updates = {}

    # Logic from spec
    import yaml as _yaml
    import tempfile, os
    mutated_yaml = state.get("mutated_spec_yaml", "")
    tmp = tempfile.NamedTemporaryFile(mode='w', suffix='.yaml', delete=False)
    tmp.write(mutated_yaml)
    tmp.close()
    try:
        spec = _yaml.safe_load(mutated_yaml)
        # Run lint on mutated spec
        try:
            from agent_ontology.lint import lint_spec
            new_lint = lint_spec(spec)
            updates["new_lint_warnings"] = [{"rule": r.code, "severity": r.severity, "message": r.message} for r in new_lint]
            print(f"    New lint: {len(new_lint)} warnings (was {len(state.get('lint_warnings', []))})")
        except Exception:
            updates["new_lint_warnings"] = []
        # Run verify on mutated spec
        try:
            from agent_ontology.verify import verify_spec
            passes, failures = verify_spec(spec, spec_path=tmp.name)
            updates["new_verify_issues"] = [{"check": f, "status": "fail"} for f in failures]
        except Exception:
            updates["new_verify_issues"] = []
        updates["new_entity_count"] = len(spec.get("entities", []))
        updates["new_process_count"] = len(spec.get("processes", []))
        updates["new_edge_count"] = len(spec.get("edges", []))
    finally:
        os.unlink(tmp.name)
    if updates.get("_done") or state.get("_done"):
        return updates

    return updates


def node_evaluate(state: AgentState) -> dict:
    """
    Evaluate Improvement
    Compare original and mutated analyses to judge improvement
    """
    print(f"  → Evaluate Improvement")
    updates = {}

    # Logic from spec
    print(f"    Evaluating improvement quality...")
    if updates.get("_done") or state.get("_done"):
        return updates

    # Flatten nested dicts
    _combined = dict(state)
    _combined.update(updates)
    for _nested_val in list(_combined.values()):
        if isinstance(_nested_val, dict):
            for _nk, _nv in _nested_val.items():
                if _nk not in _combined:
                    updates[_nk] = _nv

    # Invoke: Evaluate improvement
    _cur = dict(state)
    _cur.update(updates)
    evaluator_input = build_input(_cur, "EvaluatorInput")
    evaluator_msg = json.dumps(evaluator_input, default=str)
    evaluator_raw = invoke_evaluator(evaluator_msg, output_schema="EvaluatorOutput")
    evaluator_result = parse_response(evaluator_raw, "EvaluatorOutput")
    updates["_schema_violations"] = len(validate_output(evaluator_result, "EvaluatorOutput"))
    updates.update(evaluator_result)
    updates["evaluator_output"] = evaluator_result
    updates["evaluate_result"] = evaluator_result
    print(f"    ← Improvement Evaluator: {evaluator_result}")

    return updates


def node_accept_improvement(state: AgentState) -> dict:
    """
    Accept Improvement
    Apply the accepted mutation as the new current spec
    """
    print(f"  → Accept Improvement")
    updates = {}

    # Logic from spec
    updates["current_spec_yaml"] = state.get("mutated_spec_yaml", state.get("current_spec_yaml", ""))
    improvement = {
        "round": state.get("improvement_round", 0) + 1,
        "type": state.get("improvement_type", ""),
        "details": state.get("improvement_details", ""),
        "score_delta": state.get("score_delta", 0),
    }
    improvements = state.get("improvements_made", [])
    improvements.append(improvement)
    updates["improvements_made"] = improvements
    updates["improvement_round"] = state.get("improvement_round", 0) + 1
    print(f"    Accepted: {improvement['type']} (delta: {improvement['score_delta']:+d})")
    if updates.get("_done") or state.get("_done"):
        return updates

    return updates


def node_reject_improvement(state: AgentState) -> dict:
    """
    Reject Improvement
    Discard the mutation and increment the round counter
    """
    print(f"  → Reject Improvement")
    updates = {}

    # Logic from spec
    updates["improvement_round"] = state.get("improvement_round", 0) + 1
    print(f"    Rejected improvement (round {state.get('improvement_round', "")})")
    if updates.get("_done") or state.get("_done"):
        return updates

    return updates


def node_finalize(state: AgentState) -> dict:
    """
    Finalize
    Produce the final improved spec with improvement summary
    """
    print(f"  → Finalize")
    updates = {}

    # Logic from spec
    improvements = state.get("improvements_made", [])
    original_len = len(state.get("original_spec_yaml", ""))
    current_len = len(state.get("current_spec_yaml", ""))
    print(f"    Finalized: {len(improvements)} improvements applied")
    print(f"    Spec size: {original_len} -> {current_len} chars")
    updates["final_spec_yaml"] = state.get("current_spec_yaml", "")
    updates["total_improvements"] = len(improvements)
    updates["_done"] = True
    if updates.get("_done") or state.get("_done"):
        return updates

    return updates


# ═══════════════════════════════════════════════════════════
# Gate Routing Functions
# ═══════════════════════════════════════════════════════════

def route_check_needs_improvement(state: AgentState) -> str:
    """Gate: Needs improvement? — improvement_type is not empty"""
    if bool(state.get("improvement_type")):
        print(f"    → has improvement to make")
        return "mutate_spec"
    else:
        print(f"    → no improvement needed")
        return "finalize"


def route_check_valid(state: AgentState) -> str:
    """Gate: Mutation valid? — mutation_valid == True"""
    if state.get("mutation_valid") == True:
        print(f"    → valid mutation")
        return "reanalyze"
    else:
        print(f"    → invalid mutation")
        return "handle_invalid"


def route_check_improved(state: AgentState) -> str:
    """Gate: Improvement accepted? — improved == True"""
    if state.get("improved") == True:
        print(f"    → improvement accepted")
        return "accept_improvement"
    else:
        print(f"    → improvement rejected")
        return "reject_improvement"


def route_check_rounds_remaining(state: AgentState) -> str:
    """Gate: More rounds? — improvement_round < max_rounds"""
    if (state.get("improvement_round", 0)) < (state.get("max_rounds", 0)):
        print(f"    → rounds remaining")
        return "analyze_spec"
    else:
        print(f"    → max rounds reached")
        return "finalize"


# ═══════════════════════════════════════════════════════════
# Graph Construction
# ═══════════════════════════════════════════════════════════

def build_graph():
    graph = StateGraph(AgentState)

    graph.add_node("receive_spec", node_receive_spec)
    graph.add_node("analyze_spec", node_analyze_spec)
    graph.add_node("diagnose", node_diagnose)
    graph.add_node("mutate_spec", node_mutate_spec)
    graph.add_node("extract_mutated_yaml", node_extract_mutated_yaml)
    graph.add_node("validate_mutation", node_validate_mutation)
    graph.add_node("handle_invalid", node_handle_invalid)
    graph.add_node("reanalyze", node_reanalyze)
    graph.add_node("evaluate", node_evaluate)
    graph.add_node("accept_improvement", node_accept_improvement)
    graph.add_node("reject_improvement", node_reject_improvement)
    graph.add_node("finalize", node_finalize)

    graph.set_entry_point("receive_spec")

    graph.add_edge("receive_spec", "analyze_spec")
    graph.add_edge("analyze_spec", "diagnose")
    graph.add_conditional_edges(
        "diagnose",
        route_check_needs_improvement,
        {
            "mutate_spec": "mutate_spec",
            "finalize": "finalize",
        }
    )
    graph.add_edge("mutate_spec", "extract_mutated_yaml")
    graph.add_edge("extract_mutated_yaml", "validate_mutation")
    graph.add_conditional_edges(
        "validate_mutation",
        route_check_valid,
        {
            "reanalyze": "reanalyze",
            "handle_invalid": "handle_invalid",
        }
    )
    graph.add_edge("handle_invalid", "finalize")
    graph.add_edge("reanalyze", "evaluate")
    graph.add_conditional_edges(
        "evaluate",
        route_check_improved,
        {
            "accept_improvement": "accept_improvement",
            "reject_improvement": "reject_improvement",
        }
    )
    graph.add_conditional_edges(
        "accept_improvement",
        route_check_rounds_remaining,
        {
            "analyze_spec": "analyze_spec",
            "finalize": "finalize",
        }
    )
    graph.add_conditional_edges(
        "reject_improvement",
        route_check_rounds_remaining,
        {
            "analyze_spec": "analyze_spec",
            "finalize": "finalize",
        }
    )
    graph.add_edge("finalize", END)

    return graph.compile()


# ═══════════════════════════════════════════════════════════
# Entry Point
# ═══════════════════════════════════════════════════════════

class _StateCompat:
    """Wrapper to make LangGraph state compatible with test harness."""
    def __init__(self, state_dict):
        self.data = {k: v for k, v in state_dict.items() if not k.startswith("_")}
        self.data.update({k: v for k, v in state_dict.items() if k.startswith("_")})
        self.iteration = state_dict.get("_iteration", 0)
        self.schema_violations = state_dict.get("_schema_violations", 0)

    def get(self, key, default=None):
        return self.data.get(key, default)


MAX_ITERATIONS = int(os.environ.get("AGENT_ONTOLOGY_MAX_ITER", "100"))


def run(initial_data=None):
    """Self Improver — LangGraph execution"""
    app = build_graph()

    # Build initial state
    state = {}
    if initial_data:
        state.update(initial_data)
    state["_iteration"] = 0
    state["_schema_violations"] = 0
    state["_done"] = False

    print(f"\n════════════════════════════════════════════════════════════")
    print(f"  Self Improver (LangGraph)")
    print(f"  Reads an agent spec YAML, analyzes it for structural weaknesses (lint warnings, missing patterns, complexity issues), proposes mutations, validates the result, and outputs an improved spec.")
    print(f"════════════════════════════════════════════════════════════\n")

    # LangGraph recursion limit maps roughly to our MAX_ITERATIONS
    try:
        final_state = app.invoke(state, {"recursion_limit": MAX_ITERATIONS * 3})
    except Exception as e:
        print(f"\n  [ERROR] {type(e).__name__}: {e}")
        final_state = state

    _clean_exit = True
    dump_trace(iterations=final_state.get("_iteration", 0), clean_exit=_clean_exit)
    print(f"\nFinal state keys: {list(final_state.keys())}")
    return _StateCompat(final_state)


if __name__ == "__main__":
    run()