#!/usr/bin/env python3
"""
AlphaGeometry-style Agent — Generated by Agent Ontology Instantiation Engine
Spec: Neural-symbolic geometry solver inspired by AlphaGeometry (Trinh et al. 2024). LLM proposes construction steps; symbolic deduction engine checks validity and derives consequences. The loop continues until goal is proved or max iterations reached.

"""

import json
import os
import sys
import time
from datetime import datetime

# ═══════════════════════════════════════════════════════════
# Trace Log
# ═══════════════════════════════════════════════════════════

TRACE = []

def trace_call(agent_label, model, system_prompt, user_message, response, duration_ms):
    entry = {
        "timestamp": datetime.now().isoformat(),
        "agent": agent_label,
        "model": model,
        "system_prompt": system_prompt,
        "user_message": user_message,
        "response": response,
        "duration_ms": duration_ms,
    }
    TRACE.append(entry)
    print(f"    [{agent_label}] ({model}, {duration_ms}ms)")
    print(f"      IN:  {user_message[:300]}")
    print(f"      OUT: {response[:300]}")


def dump_trace(path="trace.json", iterations=0, clean_exit=True):
    # Compute metrics
    total_ms = sum(e["duration_ms"] for e in TRACE)
    agents_used = list(set(e["agent"] for e in TRACE))
    schema_ok = 0
    for e in TRACE:
        try:
            r = e["response"].strip()
            if r.startswith("```"): r = "\n".join(r.split("\n")[1:-1])
            json.loads(r if r.startswith("{") else r[r.find("{"):r.rfind("}")+1])
            schema_ok += 1
        except (json.JSONDecodeError, ValueError):
            pass
    est_input_tokens = sum(len(e.get("user_message",""))//4 for e in TRACE)
    est_output_tokens = sum(len(e.get("response",""))//4 for e in TRACE)
    metrics = {
        "total_llm_calls": len(TRACE),
        "total_duration_ms": total_ms,
        "avg_call_ms": total_ms // max(len(TRACE), 1),
        "iterations": iterations,
        "clean_exit": clean_exit,
        "agents_used": agents_used,
        "schema_compliance": f"{schema_ok}/{len(TRACE)}",
        "est_input_tokens": est_input_tokens,
        "est_output_tokens": est_output_tokens,
    }
    output = {"metrics": metrics, "trace": TRACE}
    with open(path, "w") as f:
        json.dump(output, f, indent=2)
    print(f"\nTrace written to {path} ({len(TRACE)} calls, {total_ms}ms total)")
    print(f"  Schema compliance: {schema_ok}/{len(TRACE)}, est tokens: ~{est_input_tokens}in/~{est_output_tokens}out")
    return metrics

# ═══════════════════════════════════════════════════════════
# LLM Call Infrastructure
# ═══════════════════════════════════════════════════════════

# Model override: set AGENT_ONTOLOGY_MODEL env var to override all agent models at runtime
_MODEL_OVERRIDE = os.environ.get("AGENT_ONTOLOGY_MODEL", "")
_OPENROUTER_API_KEY = os.environ.get("OPENROUTER_API_KEY", "")


def _openrouter_model_id(model):
    """Map spec model names to OpenRouter model IDs (provider/model format)."""
    if "/" in model:
        return model  # already in provider/model format
    if model.startswith("gemini"):
        return f"google/{model}"
    if model.startswith("claude") or model.startswith("anthropic"):
        return f"anthropic/{model}"
    if model.startswith("gpt") or model.startswith("o1") or model.startswith("o3"):
        return f"openai/{model}"
    return model  # pass through as-is


def _call_openrouter(model, system_prompt, user_message, temperature, max_tokens):
    from openai import OpenAI
    client = OpenAI(
        base_url="https://openrouter.ai/api/v1",
        api_key=_OPENROUTER_API_KEY,
    )
    response = client.chat.completions.create(
        model=_openrouter_model_id(model),
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_message},
        ],
        temperature=temperature,
        max_tokens=max_tokens,
    )
    return response.choices[0].message.content


def call_llm(model, system_prompt, user_message, temperature=0.7, max_tokens=4096, retries=3):
    if _MODEL_OVERRIDE:
        model = _MODEL_OVERRIDE
    for attempt in range(retries):
        try:
            if _OPENROUTER_API_KEY:
                return _call_openrouter(model, system_prompt, user_message, temperature, max_tokens)
            elif model.startswith("claude") or model.startswith("anthropic"):
                return _call_anthropic(model, system_prompt, user_message, temperature, max_tokens)
            elif model.startswith("gemini"):
                return _call_gemini(model, system_prompt, user_message, temperature, max_tokens)
            else:
                return _call_openai(model, system_prompt, user_message, temperature, max_tokens)
        except Exception as e:
            if attempt < retries - 1:
                wait = 2 ** attempt
                print(f"    [RETRY] {type(e).__name__}: {e} — retrying in {wait}s (attempt {attempt+1}/{retries})")
                import time as _time; _time.sleep(wait)
            else:
                print(f"    [FAIL] {type(e).__name__}: {e} after {retries} attempts")
                return json.dumps({"stub": True, "model": model, "error": str(e)})


def _call_openai(model, system_prompt, user_message, temperature, max_tokens):
    from openai import OpenAI
    client = OpenAI()
    response = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_message},
        ],
        temperature=temperature,
        max_tokens=max_tokens,
    )
    return response.choices[0].message.content


def _call_anthropic(model, system_prompt, user_message, temperature, max_tokens):
    import anthropic
    client = anthropic.Anthropic()
    response = client.messages.create(
        model=model,
        max_tokens=max_tokens,
        system=system_prompt,
        messages=[{"role": "user", "content": user_message}],
    )
    return response.content[0].text


def _call_gemini(model, system_prompt, user_message, temperature, max_tokens):
    from google import genai
    client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY", ""))
    response = client.models.generate_content(
        model=model,
        contents=f"{system_prompt}\n\n{user_message}",
        config={"temperature": temperature, "max_output_tokens": max_tokens},
    )
    return response.text


def call_embedding(texts, model="text-embedding-3-small", provider="openai"):
    """Generate embeddings for a list of texts. Returns list of float vectors."""
    if isinstance(texts, str):
        texts = [texts]
    if provider == "openai" or model.startswith("text-embedding"):
        from openai import OpenAI
        client = OpenAI()
        response = client.embeddings.create(model=model, input=texts)
        return [item.embedding for item in response.data]
    elif provider == "google" or model.startswith("models/"):
        from google import genai
        client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY", ""))
        result = client.models.embed_content(model=model or "models/text-embedding-004", contents=texts)
        return result.embeddings
    elif provider == "huggingface" or provider == "local":
        try:
            from sentence_transformers import SentenceTransformer
            _emb_model = SentenceTransformer(model or "all-MiniLM-L6-v2")
            return _emb_model.encode(texts).tolist()
        except ImportError:
            print("    [WARN] sentence-transformers not installed, returning empty embeddings")
            return [[] for _ in texts]
    else:
        from openai import OpenAI
        client = OpenAI()
        response = client.embeddings.create(model=model, input=texts)
        return [item.embedding for item in response.data]

# ═══════════════════════════════════════════════════════════
# Schema Registry
# ═══════════════════════════════════════════════════════════

SCHEMAS = {
    "ConstructionInput": {
        "description": """""",
        "fields": [{"name": "problem", "type": "string"}, {"name": "known_facts", "type": "list<string>"}, {"name": "goal", "type": "string"}],
    },
    "ConstructionOutput": {
        "description": """""",
        "fields": [{"name": "construction", "type": "string"}, {"name": "formal", "type": "string"}],
    },
    "DeductionResult": {
        "description": """""",
        "fields": [{"name": "new_facts", "type": "list<string>"}, {"name": "goal_proved", "type": "boolean"}],
    },
}


def validate_output(data, schema_name):
    """Validate parsed LLM output against schema. Returns list of issues."""
    schema = SCHEMAS.get(schema_name)
    if not schema or "raw" in data:
        return []
    issues = []
    for field in schema["fields"]:
        fname = field["name"]
        ftype = field["type"]
        if fname not in data:
            issues.append(f"Missing field '{fname}' ({ftype})")
            continue
        val = data[fname]
        if ftype == "string" and not isinstance(val, str):
            issues.append(f"Field '{fname}' expected string, got {type(val).__name__}")
        elif ftype == "integer" and not isinstance(val, (int, float)):
            issues.append(f"Field '{fname}' expected integer, got {type(val).__name__}")
        elif ftype.startswith("list") and not isinstance(val, list):
            issues.append(f"Field '{fname}' expected list, got {type(val).__name__}")
        elif ftype.startswith("enum["):
            allowed = [v.strip() for v in ftype[5:-1].split(",")]
            if val not in allowed:
                issues.append(f"Field '{fname}' value '{val}' not in {allowed}")
    if issues:
        print(f"    [SCHEMA] {schema_name}: {len(issues)} issue(s): {issues[0]}")
    return issues


def build_input(state, schema_name):
    """Build an input dict for an agent call using schema field names.
    Pulls matching keys from state.data, checking both flat keys and
    values nested inside dict entries (e.g. state.data["xxx_input"]["field"])."""
    schema = SCHEMAS.get(schema_name)
    if not schema:
        return state.data
    result = {}
    for field in schema["fields"]:
        fname = field["name"]
        if fname in state.data:
            result[fname] = state.data[fname]
        else:
            # Search nested dicts in state.data for the field
            for _k, _v in state.data.items():
                if isinstance(_v, dict) and fname in _v:
                    result[fname] = _v[fname]
                    break
    return result


def output_instruction(schema_name):
    """Generate a JSON output instruction string for the LLM."""
    schema = SCHEMAS.get(schema_name)
    if not schema:
        return ""
    fields = ", ".join(f'"{f["name"]}": <{f["type"]}>' for f in schema["fields"])
    return f"\n\nRespond with ONLY valid JSON matching this schema: {{{fields}}}"


def parse_response(response, schema_name):
    """Parse an LLM response according to an output schema.
    Returns a dict of field values, or {"raw": response} if parsing fails."""
    import re as _re
    text = response.strip()
    # Handle markdown code blocks
    if text.startswith("```"):
        lines = text.split("\n")
        lines = lines[1:]  # skip ```json
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        text = "\n".join(lines)
    # Attempt 1: direct parse
    try:
        parsed = json.loads(text)
        if isinstance(parsed, dict):
            return parsed
        return {"value": parsed}
    except json.JSONDecodeError:
        pass
    # Attempt 2: extract JSON object from prose
    start = text.find("{")
    end = text.rfind("}") + 1
    if start >= 0 and end > start:
        candidate = text[start:end]
        try:
            return json.loads(candidate)
        except json.JSONDecodeError:
            pass
        # Attempt 3: fix trailing commas
        fixed = _re.sub(r",\s*}", "}", candidate)
        fixed = _re.sub(r",\s*]", "]", fixed)
        try:
            return json.loads(fixed)
        except json.JSONDecodeError:
            pass
        # Attempt 4: find matching braces (handle nested)
        depth = 0
        for i, ch in enumerate(text[start:], start):
            if ch == "{": depth += 1
            elif ch == "}": depth -= 1
            if depth == 0:
                try:
                    return json.loads(text[start:i+1])
                except json.JSONDecodeError:
                    break
    return {"raw": response}


# ═══════════════════════════════════════════════════════════
# Stores
# ═══════════════════════════════════════════════════════════

class Store_fact_store:
    """Derived Facts (logic_program)"""
    def __init__(self):
        self.data = {}
        self._rules = []

    def read(self, key=None):
        if key is None:
            return self._rules
        return [r for r in self._rules if key in str(r)]

    def write(self, value, key=None):
        self._rules.append(value)



# ═══════════════════════════════════════════════════════════
# Agent Wrappers
# ═══════════════════════════════════════════════════════════

def invoke_construction_proposer(user_message, output_schema=None):
    """Construction Proposer (LLM)"""
    system = """You are a geometry construction proposer. Given a geometry problem and the current known facts (derived by symbolic deduction), propose a single auxiliary construction (e.g., "construct midpoint M of segment AB" or "draw line through P parallel to AB"). Output JSON: {"construction": "description", "formal": "formal notation"}
"""
    if output_schema:
        system += output_instruction(output_schema)
    t0 = time.time()
    result = call_llm(
        model="gemini-3-flash-preview",
        system_prompt=system,
        user_message=user_message,
        temperature=0.7,
        max_tokens=4096,
    )
    trace_call("Construction Proposer (LLM)", "gemini-3-flash-preview", system, user_message, result, int((time.time()-t0)*1000))
    return result



# ═══════════════════════════════════════════════════════════
# Agent State
# ═══════════════════════════════════════════════════════════

class AgentState:
    """Runtime state for AlphaGeometry-style Agent"""
    def __init__(self):
        self.fact_store = Store_fact_store()
        self.data = {}  # current data flowing through the pipeline
        self.iteration = 0
        self.schema_violations = 0


# ═══════════════════════════════════════════════════════════
# Process Functions
# ═══════════════════════════════════════════════════════════

def process_receive_problem(state):
    """
    Receive Geometry Problem
    """
    print(f"  → Receive Geometry Problem")

    # Logic from spec
    state.data["problem"] = state.data.get("problem", state.data.get("query", ""))
    state.data["goal"] = state.data.get("goal", "Prove triangle ABC is isosceles")
    state.data["known_facts"] = state.data.get("known_facts", ["AB = AC", "angle BAC = 60"])
    state.data["iteration"] = 0
    state.data["max_iterations"] = state.data.get("max_iterations", 5)
    state.data["proof_steps"] = []
    if state.data.get("_done"):
        return state

    return state


def process_propose_construction(state):
    """
    Propose Construction
    """
    print(f"  → Propose Construction")

    # Invoke: construction_proposer
    construction_proposer_input = build_input(state, "ConstructionInput")
    construction_proposer_msg = json.dumps(construction_proposer_input, default=str)
    construction_proposer_raw = invoke_construction_proposer(construction_proposer_msg, output_schema="ConstructionOutput")
    construction_proposer_result = parse_response(construction_proposer_raw, "ConstructionOutput")
    # Validate and merge output fields into state.data
    state.schema_violations += len(validate_output(construction_proposer_result, "ConstructionOutput"))
    state.data.update(construction_proposer_result)
    state.data["construction_output"] = construction_proposer_result
    state.data["propose_construction_result"] = construction_proposer_result
    print(f"    ← Construction Proposer (LLM): {construction_proposer_result}")

    return state


def process_translate_to_formal(state):
    """
    Construction → Formal Rules
    """
    print(f"  → Construction → Formal Rules")



def process_run_deduction(state):
    """
    Symbolic Deduction Engine
    """
    print(f"  → Symbolic Deduction Engine")



def process_check_proved(state):
    """
    Goal Proved?
    """
    print(f"  → Goal Proved?")

    # Gate: goal_proved
    # Branch: goal_proved is true → emit_proof
    # Branch: goal_proved is false → check_iterations

    if bool(state.data.get("goal_proved")):
        print(f"    → goal_proved is true")
        return "emit_proof"
    else:
        print(f"    → goal_proved is false")
        return "check_iterations"


def process_check_iterations(state):
    """
    Iterations Remaining?
    """
    print(f"  → Iterations Remaining?")

    # Gate: iteration < max_iterations
    # Branch: iteration < max_iterations → propose_construction
    # Branch: iteration >= max_iterations → emit_failure

    if (state.data.get("iteration", 0)) < (state.data.get("max_iterations", 0)):
        print(f"    → iteration < max_iterations")
        return "propose_construction"
    else:
        print(f"    → iteration >= max_iterations")
        return "emit_failure"


def process_update_facts(state):
    """
    Update Known Facts
    """
    print(f"  → Update Known Facts")

    # Logic from spec
    new_facts = state.data.get("new_facts", [])
    state.data["known_facts"] = state.data.get("known_facts", []) + new_facts
    state.data["iteration"] = state.data.get("iteration", 0) + 1
    construction = state.data.get("construction", "")
    if construction:
        state.data["proof_steps"] = state.data.get("proof_steps", []) + [construction]
    if state.data.get("_done"):
        return state

    return state


def process_emit_proof(state):
    """
    Emit Proof
    """
    print(f"  → Emit Proof")

    # Logic from spec
    state.data["proved"] = True
    state.data["answer"] = "Proof found: " + "; ".join(state.data.get("proof_steps", []))
    state.data["_done"] = True
    if state.data.get("_done"):
        return state

    return state


def process_emit_failure(state):
    """
    Emit Failure
    """
    print(f"  → Emit Failure")

    # Logic from spec
    state.data["proved"] = False
    state.data["answer"] = "Could not prove within iteration limit."
    state.data["_done"] = True
    if state.data.get("_done"):
        return state

    return state


def process_handle_timeout(state):
    """
    Handle Deduction Timeout
    """
    print(f"  → Handle Deduction Timeout")

    # Logic from spec
    state.data["new_facts"] = []
    state.data["goal_proved"] = False
    if state.data.get("_done"):
        return state

    return state


# ═══════════════════════════════════════════════════════════
# State Machine Executor
# ═══════════════════════════════════════════════════════════

PROCESSES = {
    "receive_problem": process_receive_problem,
    "propose_construction": process_propose_construction,
    "translate_to_formal": process_translate_to_formal,
    "run_deduction": process_run_deduction,
    "check_proved": process_check_proved,
    "check_iterations": process_check_iterations,
    "update_facts": process_update_facts,
    "emit_proof": process_emit_proof,
    "emit_failure": process_emit_failure,
    "handle_timeout": process_handle_timeout,
}

TRANSITIONS = {
    "receive_problem": "propose_construction",
    "propose_construction": "translate_to_formal",
    "translate_to_formal": "run_deduction",
    "run_deduction": "update_facts",
    # "check_proved": determined by gate logic
    # "check_iterations": determined by gate logic
    "update_facts": "check_proved",
    "emit_proof": None,  # terminal
    "emit_failure": None,  # terminal
    "handle_timeout": "update_facts",
}


MAX_ITERATIONS = int(os.environ.get("AGENT_ONTOLOGY_MAX_ITER", "100"))


def run(initial_data=None):
    """AlphaGeometry-style Agent — main execution loop"""
    state = AgentState()
    if initial_data:
        state.data.update(initial_data)

    current = "receive_problem"
    print(f"\n════════════════════════════════════════════════════════════")
    print(f"  AlphaGeometry-style Agent")
    print(f"  Neural-symbolic geometry solver inspired by AlphaGeometry (Trinh et al. 2024). LLM proposes construction steps; symbolic deduction engine checks validity and derives consequences. The loop continues until goal is proved or max iterations reached.")
    print(f"════════════════════════════════════════════════════════════\n")

    while current and state.iteration < MAX_ITERATIONS:
        state.iteration += 1
        print(f"\n[Iteration {state.iteration}] State: {current}")

        process_fn = PROCESSES.get(current)
        if not process_fn:
            print(f"  Unknown process: {current}")
            break

        result = process_fn(state)

        if current in ['check_proved', 'check_iterations']:
            current = result
        else:
            current = TRANSITIONS.get(current)

        # Fan-out: if transition is a list, run all branches sequentially
        while isinstance(current, list):
            _targets = current
            for _ft in _targets:
                state.iteration += 1
                print(f"\n[Iteration {state.iteration}] State: {_ft} (fan-out)")
                _fn = PROCESSES.get(_ft)
                if _fn:
                    _fn(state)
            # Collect unique next-hops from all fan-out targets
            _next_set = []
            for _ft in _targets:
                _nt = TRANSITIONS.get(_ft)
                if _nt is not None and _nt not in _next_set:
                    _next_set.append(_nt)
            current = _next_set[0] if len(_next_set) == 1 else (_next_set if _next_set else None)

        if current is None or state.data.get("_done"):
            print("\n  [DONE] Reached terminal state.")
            break

    _clean_exit = state.iteration < MAX_ITERATIONS
    if state.iteration >= MAX_ITERATIONS:
        print(f"\n  [STOPPED] Max iterations ({MAX_ITERATIONS}) reached.")
        _clean_exit = False

    if state.schema_violations > 0:
        print(f"\n  [SCHEMA] {state.schema_violations} total schema violation(s) during execution")
    dump_trace(iterations=state.iteration, clean_exit=_clean_exit)
    print(f"\nFinal state.data keys: {list(state.data.keys())}")
    return state


if __name__ == "__main__":
    run()