#!/usr/bin/env python3
"""
Language Agent Tree Search (LATS) — Generated by Agent Ontology Instantiation Engine
Spec: Iterative problem solving using Monte Carlo Tree Search (MCTS) combined with LLM-based action generation and state evaluation.
"""

import json
import os
import sys
import time
from datetime import datetime

# ═══════════════════════════════════════════════════════════
# Trace Log
# ═══════════════════════════════════════════════════════════

TRACE = []

def trace_call(agent_label, model, system_prompt, user_message, response, duration_ms):
    entry = {
        "timestamp": datetime.now().isoformat(),
        "agent": agent_label,
        "model": model,
        "system_prompt": system_prompt,
        "user_message": user_message,
        "response": response,
        "duration_ms": duration_ms,
    }
    TRACE.append(entry)
    print(f"    [{agent_label}] ({model}, {duration_ms}ms)")
    print(f"      IN:  {user_message[:300]}")
    print(f"      OUT: {response[:300]}")


def dump_trace(path="trace.json", iterations=0, clean_exit=True):
    # Compute metrics
    total_ms = sum(e["duration_ms"] for e in TRACE)
    agents_used = list(set(e["agent"] for e in TRACE))
    schema_ok = 0
    for e in TRACE:
        try:
            r = e["response"].strip()
            if r.startswith("```"): r = "\n".join(r.split("\n")[1:-1])
            json.loads(r if r.startswith("{") else r[r.find("{"):r.rfind("}")+1])
            schema_ok += 1
        except (json.JSONDecodeError, ValueError):
            pass
    est_input_tokens = sum(len(e.get("user_message",""))//4 for e in TRACE)
    est_output_tokens = sum(len(e.get("response",""))//4 for e in TRACE)
    metrics = {
        "total_llm_calls": len(TRACE),
        "total_duration_ms": total_ms,
        "avg_call_ms": total_ms // max(len(TRACE), 1),
        "iterations": iterations,
        "clean_exit": clean_exit,
        "agents_used": agents_used,
        "schema_compliance": f"{schema_ok}/{len(TRACE)}",
        "est_input_tokens": est_input_tokens,
        "est_output_tokens": est_output_tokens,
    }
    output = {"metrics": metrics, "trace": TRACE}
    with open(path, "w") as f:
        json.dump(output, f, indent=2)
    print(f"\nTrace written to {path} ({len(TRACE)} calls, {total_ms}ms total)")
    print(f"  Schema compliance: {schema_ok}/{len(TRACE)}, est tokens: ~{est_input_tokens}in/~{est_output_tokens}out")
    return metrics

# ═══════════════════════════════════════════════════════════
# LLM Call Infrastructure
# ═══════════════════════════════════════════════════════════

# Model override: set AGENT_ONTOLOGY_MODEL env var to override all agent models at runtime
_MODEL_OVERRIDE = os.environ.get("AGENT_ONTOLOGY_MODEL", "")
_OPENROUTER_API_KEY = os.environ.get("OPENROUTER_API_KEY", "")


def _openrouter_model_id(model):
    """Map spec model names to OpenRouter model IDs (provider/model format)."""
    if "/" in model:
        return model  # already in provider/model format
    if model.startswith("gemini"):
        return f"google/{model}"
    if model.startswith("claude") or model.startswith("anthropic"):
        return f"anthropic/{model}"
    if model.startswith("gpt") or model.startswith("o1") or model.startswith("o3"):
        return f"openai/{model}"
    return model  # pass through as-is


def _call_openrouter(model, system_prompt, user_message, temperature, max_tokens):
    from openai import OpenAI
    client = OpenAI(
        base_url="https://openrouter.ai/api/v1",
        api_key=_OPENROUTER_API_KEY,
    )
    response = client.chat.completions.create(
        model=_openrouter_model_id(model),
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_message},
        ],
        temperature=temperature,
        max_tokens=max_tokens,
    )
    return response.choices[0].message.content


def call_llm(model, system_prompt, user_message, temperature=0.7, max_tokens=4096, retries=3):
    if _MODEL_OVERRIDE:
        model = _MODEL_OVERRIDE
    for attempt in range(retries):
        try:
            if _OPENROUTER_API_KEY:
                return _call_openrouter(model, system_prompt, user_message, temperature, max_tokens)
            elif model.startswith("claude") or model.startswith("anthropic"):
                return _call_anthropic(model, system_prompt, user_message, temperature, max_tokens)
            elif model.startswith("gemini"):
                return _call_gemini(model, system_prompt, user_message, temperature, max_tokens)
            else:
                return _call_openai(model, system_prompt, user_message, temperature, max_tokens)
        except Exception as e:
            if attempt < retries - 1:
                wait = 2 ** attempt
                print(f"    [RETRY] {type(e).__name__}: {e} — retrying in {wait}s (attempt {attempt+1}/{retries})")
                import time as _time; _time.sleep(wait)
            else:
                print(f"    [FAIL] {type(e).__name__}: {e} after {retries} attempts")
                return json.dumps({"stub": True, "model": model, "error": str(e)})


def _call_openai(model, system_prompt, user_message, temperature, max_tokens):
    from openai import OpenAI
    client = OpenAI()
    response = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_message},
        ],
        temperature=temperature,
        max_tokens=max_tokens,
    )
    return response.choices[0].message.content


def _call_anthropic(model, system_prompt, user_message, temperature, max_tokens):
    import anthropic
    client = anthropic.Anthropic()
    response = client.messages.create(
        model=model,
        max_tokens=max_tokens,
        system=system_prompt,
        messages=[{"role": "user", "content": user_message}],
    )
    return response.content[0].text


def _call_gemini(model, system_prompt, user_message, temperature, max_tokens):
    from google import genai
    client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY", ""))
    response = client.models.generate_content(
        model=model,
        contents=f"{system_prompt}\n\n{user_message}",
        config={"temperature": temperature, "max_output_tokens": max_tokens},
    )
    return response.text

# ═══════════════════════════════════════════════════════════
# Schema Registry
# ═══════════════════════════════════════════════════════════

SCHEMAS = {
    "LATSInput": {
        "description": """""",
        "fields": [{"name": "query", "type": "string"}],
    },
    "ExpansionInput": {
        "description": """""",
        "fields": [{"name": "problem", "type": "string"}, {"name": "trajectory", "type": "string"}],
    },
    "ActionGeneratorOutput": {
        "description": """""",
        "fields": [{"name": "actions", "type": "list<string>"}],
    },
    "EvaluationInput": {
        "description": """""",
        "fields": [{"name": "problem", "type": "string"}, {"name": "trajectory", "type": "string"}, {"name": "new_state", "type": "string"}],
    },
    "StateEvaluatorOutput": {
        "description": """""",
        "fields": [{"name": "score", "type": "float"}, {"name": "is_terminal", "type": "boolean"}],
    },
    "FormatterInput": {
        "description": """""",
        "fields": [{"name": "problem", "type": "string"}, {"name": "best_trajectory", "type": "string"}],
    },
    "FinalSolution": {
        "description": """""",
        "fields": [{"name": "answer", "type": "string"}],
    },
    "TreeData": {
        "description": """""",
        "fields": [{"name": "tree", "type": "object"}, {"name": "iteration", "type": "integer"}, {"name": "best_score", "type": "float"}],
    },
}


def validate_output(data, schema_name):
    """Validate parsed LLM output against schema. Returns list of issues."""
    schema = SCHEMAS.get(schema_name)
    if not schema or "raw" in data:
        return []
    issues = []
    for field in schema["fields"]:
        fname = field["name"]
        ftype = field["type"]
        if fname not in data:
            issues.append(f"Missing field '{fname}' ({ftype})")
            continue
        val = data[fname]
        if ftype == "string" and not isinstance(val, str):
            issues.append(f"Field '{fname}' expected string, got {type(val).__name__}")
        elif ftype == "integer" and not isinstance(val, (int, float)):
            issues.append(f"Field '{fname}' expected integer, got {type(val).__name__}")
        elif ftype.startswith("list") and not isinstance(val, list):
            issues.append(f"Field '{fname}' expected list, got {type(val).__name__}")
        elif ftype.startswith("enum["):
            allowed = [v.strip() for v in ftype[5:-1].split(",")]
            if val not in allowed:
                issues.append(f"Field '{fname}' value '{val}' not in {allowed}")
    if issues:
        print(f"    [SCHEMA] {schema_name}: {len(issues)} issue(s): {issues[0]}")
    return issues


def build_input(state, schema_name):
    """Build an input dict for an agent call using schema field names.
    Pulls matching keys from state.data, checking both flat keys and
    values nested inside dict entries (e.g. state.data["xxx_input"]["field"])."""
    schema = SCHEMAS.get(schema_name)
    if not schema:
        return state.data
    result = {}
    for field in schema["fields"]:
        fname = field["name"]
        if fname in state.data:
            result[fname] = state.data[fname]
        else:
            # Search nested dicts in state.data for the field
            for _k, _v in state.data.items():
                if isinstance(_v, dict) and fname in _v:
                    result[fname] = _v[fname]
                    break
    return result


def output_instruction(schema_name):
    """Generate a JSON output instruction string for the LLM."""
    schema = SCHEMAS.get(schema_name)
    if not schema:
        return ""
    fields = ", ".join(f'"{f["name"]}": <{f["type"]}>' for f in schema["fields"])
    return f"\n\nRespond with ONLY valid JSON matching this schema: {{{fields}}}"


def parse_response(response, schema_name):
    """Parse an LLM response according to an output schema.
    Returns a dict of field values, or {"raw": response} if parsing fails."""
    import re as _re
    text = response.strip()
    # Handle markdown code blocks
    if text.startswith("```"):
        lines = text.split("\n")
        lines = lines[1:]  # skip ```json
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        text = "\n".join(lines)
    # Attempt 1: direct parse
    try:
        parsed = json.loads(text)
        if isinstance(parsed, dict):
            return parsed
        return {"value": parsed}
    except json.JSONDecodeError:
        pass
    # Attempt 2: extract JSON object from prose
    start = text.find("{")
    end = text.rfind("}") + 1
    if start >= 0 and end > start:
        candidate = text[start:end]
        try:
            return json.loads(candidate)
        except json.JSONDecodeError:
            pass
        # Attempt 3: fix trailing commas
        fixed = _re.sub(r",\s*}", "}", candidate)
        fixed = _re.sub(r",\s*]", "]", fixed)
        try:
            return json.loads(fixed)
        except json.JSONDecodeError:
            pass
        # Attempt 4: find matching braces (handle nested)
        depth = 0
        for i, ch in enumerate(text[start:], start):
            if ch == "{": depth += 1
            elif ch == "}": depth -= 1
            if depth == 0:
                try:
                    return json.loads(text[start:i+1])
                except json.JSONDecodeError:
                    break
    return {"raw": response}


# ═══════════════════════════════════════════════════════════
# Stores
# ═══════════════════════════════════════════════════════════

class Store_tree_store:
    """MCTS Tree Store (blackboard)"""
    def __init__(self):
        self.data = {}

    def read(self, key=None):
        return self.data if key is None else self.data.get(key)

    def write(self, value, key=None):
        if key is not None:
            self.data[key] = value
        else:
            self.data = value



# ═══════════════════════════════════════════════════════════
# Agent Wrappers
# ═══════════════════════════════════════════════════════════

def invoke_action_generator(user_message, output_schema=None):
    """Action Generator"""
    system = """You are the expansion phase of an MCTS agent. Given a problem statement and a trajectory of previous actions/states, generate candidate next actions.
Provide a list of potential actions that could lead toward a solution.
"""
    if output_schema:
        system += output_instruction(output_schema)
    t0 = time.time()
    result = call_llm(
        model="gemini-3-flash-preview",
        system_prompt=system,
        user_message=user_message,
        temperature=0.7,
        max_tokens=4096,
    )
    trace_call("Action Generator", "gemini-3-flash-preview", system, user_message, result, int((time.time()-t0)*1000))
    return result


def invoke_state_evaluator(user_message, output_schema=None):
    """State Evaluator"""
    system = """You are the evaluation phase of an MCTS agent. Given a problem and a trajectory ending in a new state, evaluate the state.
Assign a value from 0 to 1 (0 = dead end, 1 = solution). 
Identify if the state is 'terminal' (problem solved) or a 'dead_end'.
"""
    if output_schema:
        system += output_instruction(output_schema)
    t0 = time.time()
    result = call_llm(
        model="gemini-3-flash-preview",
        system_prompt=system,
        user_message=user_message,
        temperature=0.7,
        max_tokens=4096,
    )
    trace_call("State Evaluator", "gemini-3-flash-preview", system, user_message, result, int((time.time()-t0)*1000))
    return result


def invoke_solution_formatter(user_message, output_schema=None):
    """Solution Formatter"""
    system = """You are the final output phase. Given the best trajectory found during the tree search, format it into a clear, concise final answer for the user.
"""
    if output_schema:
        system += output_instruction(output_schema)
    t0 = time.time()
    result = call_llm(
        model="gemini-3-flash-preview",
        system_prompt=system,
        user_message=user_message,
        temperature=0.7,
        max_tokens=4096,
    )
    trace_call("Solution Formatter", "gemini-3-flash-preview", system, user_message, result, int((time.time()-t0)*1000))
    return result



# ═══════════════════════════════════════════════════════════
# Agent State
# ═══════════════════════════════════════════════════════════

class AgentState:
    """Runtime state for Language Agent Tree Search (LATS)"""
    def __init__(self):
        self.tree_store = Store_tree_store()
        self.data = {}  # current data flowing through the pipeline
        self.iteration = 0
        self.schema_violations = 0


# ═══════════════════════════════════════════════════════════
# Process Functions
# ═══════════════════════════════════════════════════════════

def process_initialize_search(state):
    """
    Initialize Search
    Setup the root node and search parameters
    """
    print(f"  → Initialize Search")

    # Logic from spec
    state.data["iteration"] = 0
    state.data["is_terminal"] = False
    state.data["best_score"] = 0.0
    state.data["tree"] = {"root": {"query": state.data.get("query"), "children": [], "visits": 0, "value": 0}}
    print(f"Starting LATS for: {state.data.get('query')}")
    if state.data.get("_done"):
        return state

    return state


def process_select_node(state):
    """
    Selection
    Select a leaf node to expand using UCT logic
    """
    print(f"  → Selection")

    # Read: Read Tree State
    tree_store_data = state.tree_store.read()
    state.data["tree_store"] = tree_store_data

    # Logic from spec
    # Logic to traverse the tree in state.data['tree'] using UCT
    # For this spec, we identify the 'current_trajectory' to expand
    state.data["current_trajectory"] = state.data.get("tree", {}).get("root", {}).get("query", "")
    print(f"Selecting node for iteration {state.data['iteration']}")
    if state.data.get("_done"):
        return state

    return state


def process_expand_node(state):
    """
    Expansion
    Generate candidate actions for the selected node
    """
    print(f"  → Expansion")

    # Logic from spec
    state.data["expansion_input"] = {
      "problem": state.data.get("query"),
      "trajectory": state.data.get("current_trajectory")
    }
    if state.data.get("_done"):
        return state

    # Flatten nested dicts: promote schema fields to top-level state.data
    for _nested_val in list(state.data.values()):
        if isinstance(_nested_val, dict):
            for _nk, _nv in _nested_val.items():
                if _nk not in state.data:
                    state.data[_nk] = _nv

    # Invoke: action_generator
    action_generator_input = build_input(state, "ExpansionInput")
    action_generator_msg = json.dumps(action_generator_input, default=str)
    action_generator_raw = invoke_action_generator(action_generator_msg, output_schema="ActionGeneratorOutput")
    action_generator_result = parse_response(action_generator_raw, "ActionGeneratorOutput")
    # Validate and merge output fields into state.data
    state.schema_violations += len(validate_output(action_generator_result, "ActionGeneratorOutput"))
    state.data.update(action_generator_result)
    state.data["action_generator_output"] = action_generator_result
    state.data["expand_node_result"] = action_generator_result
    print(f"    ← Action Generator: {action_generator_result}")

    return state


def process_evaluate_node(state):
    """
    Evaluation
    Evaluate the newly generated states
    """
    print(f"  → Evaluation")

    # Logic from spec
    # Prepare input for the evaluator based on the last action from action_generator
    actions = state.data.get("action_generator_output", {}).get("actions", [])
    state.data["evaluation_input"] = {
      "problem": state.data.get("query"),
      "trajectory": state.data.get("current_trajectory"),
      "new_state": actions[0] if actions else "No action"
    }
    if state.data.get("_done"):
        return state

    # Flatten nested dicts: promote schema fields to top-level state.data
    for _nested_val in list(state.data.values()):
        if isinstance(_nested_val, dict):
            for _nk, _nv in _nested_val.items():
                if _nk not in state.data:
                    state.data[_nk] = _nv

    # Invoke: state_evaluator
    state_evaluator_input = build_input(state, "EvaluationInput")
    state_evaluator_msg = json.dumps(state_evaluator_input, default=str)
    state_evaluator_raw = invoke_state_evaluator(state_evaluator_msg, output_schema="StateEvaluatorOutput")
    state_evaluator_result = parse_response(state_evaluator_raw, "StateEvaluatorOutput")
    # Validate and merge output fields into state.data
    state.schema_violations += len(validate_output(state_evaluator_result, "StateEvaluatorOutput"))
    state.data.update(state_evaluator_result)
    state.data["state_evaluator_output"] = state_evaluator_result
    state.data["evaluate_node_result"] = state_evaluator_result
    print(f"    ← State Evaluator: {state_evaluator_result}")

    return state


def process_backpropagate(state):
    """
    Backpropagation
    Update tree statistics with the evaluation result
    """
    print(f"  → Backpropagation")

    # Logic from spec
    eval_result = state.data.get("state_evaluator_output", {})
    score = eval_result.get("score", 0.0)
    state.data["is_terminal"] = eval_result.get("is_terminal", False)
    state.data["iteration"] += 1
    if score > state.data["best_score"]:
        state.data["best_score"] = score
        state.data["best_trajectory"] = state.data.get("current_trajectory")
    print(f"Iteration {state.data['iteration']} complete. Score: {score}")
    if state.data.get("_done"):
        return state

    # Write: Update Tree
    state.tree_store.write(state.data.copy())

    return state


def process_check_termination(state):
    """
    Search Finished?
    """
    print(f"  → Search Finished?")

    # Gate: is_terminal == True or iteration >= 30
    # Branch: continue → select_node
    # Branch: finish → format_output

    if (state.data.get("is_terminal") == True) or ((state.data.get("iteration", 0)) >= 30):
        print(f"    → continue")
        return "select_node"
    else:
        print(f"    → finish")
        return "format_output"


def process_format_output(state):
    """
    Format Output
    Prepare the final solution
    """
    print(f"  → Format Output")

    # Logic from spec
    state.data["formatter_input"] = {
      "problem": state.data.get("query"),
      "best_trajectory": state.data.get("best_trajectory", "No solution found")
    }
    if state.data.get("_done"):
        return state

    # Flatten nested dicts: promote schema fields to top-level state.data
    for _nested_val in list(state.data.values()):
        if isinstance(_nested_val, dict):
            for _nk, _nv in _nested_val.items():
                if _nk not in state.data:
                    state.data[_nk] = _nv

    # Invoke: solution_formatter
    solution_formatter_input = build_input(state, "FormatterInput")
    solution_formatter_msg = json.dumps(solution_formatter_input, default=str)
    solution_formatter_raw = invoke_solution_formatter(solution_formatter_msg, output_schema="FinalSolution")
    solution_formatter_result = parse_response(solution_formatter_raw, "FinalSolution")
    # Validate and merge output fields into state.data
    state.schema_violations += len(validate_output(solution_formatter_result, "FinalSolution"))
    state.data.update(solution_formatter_result)
    state.data["final_solution"] = solution_formatter_result
    state.data["format_output_result"] = solution_formatter_result
    print(f"    ← Solution Formatter: {solution_formatter_result}")

    return state


def process_finalize(state):
    """
    Finalize
    """
    print(f"  → Finalize")

    # Logic from spec
    state.data["_done"] = True
    print("LATS process complete.")
    if state.data.get("_done"):
        return state

    return state


# ═══════════════════════════════════════════════════════════
# State Machine Executor
# ═══════════════════════════════════════════════════════════

PROCESSES = {
    "initialize_search": process_initialize_search,
    "select_node": process_select_node,
    "expand_node": process_expand_node,
    "evaluate_node": process_evaluate_node,
    "backpropagate": process_backpropagate,
    "check_termination": process_check_termination,
    "format_output": process_format_output,
    "finalize": process_finalize,
}

TRANSITIONS = {
    "initialize_search": "select_node",
    "select_node": "expand_node",
    "expand_node": "evaluate_node",
    "evaluate_node": "backpropagate",
    "backpropagate": "check_termination",
    # "check_termination": determined by gate logic
    "format_output": "finalize",
    "finalize": None,  # terminal
}


MAX_ITERATIONS = int(os.environ.get("AGENT_ONTOLOGY_MAX_ITER", "100"))


def run(initial_data=None):
    """Language Agent Tree Search (LATS) — main execution loop"""
    state = AgentState()
    if initial_data:
        state.data.update(initial_data)

    current = "initialize_search"
    print(f"\n════════════════════════════════════════════════════════════")
    print(f"  Language Agent Tree Search (LATS)")
    print(f"  Iterative problem solving using Monte Carlo Tree Search (MCTS) combined with LLM-based action generation and state evaluation.")
    print(f"════════════════════════════════════════════════════════════\n")

    while current and state.iteration < MAX_ITERATIONS:
        state.iteration += 1
        print(f"\n[Iteration {state.iteration}] State: {current}")

        process_fn = PROCESSES.get(current)
        if not process_fn:
            print(f"  Unknown process: {current}")
            break

        result = process_fn(state)

        if current in ['check_termination']:
            current = result
        else:
            current = TRANSITIONS.get(current)

        # Fan-out: if transition is a list, run all branches sequentially
        while isinstance(current, list):
            _targets = current
            for _ft in _targets:
                state.iteration += 1
                print(f"\n[Iteration {state.iteration}] State: {_ft} (fan-out)")
                _fn = PROCESSES.get(_ft)
                if _fn:
                    _fn(state)
            # Collect unique next-hops from all fan-out targets
            _next_set = []
            for _ft in _targets:
                _nt = TRANSITIONS.get(_ft)
                if _nt is not None and _nt not in _next_set:
                    _next_set.append(_nt)
            current = _next_set[0] if len(_next_set) == 1 else (_next_set if _next_set else None)

        if current is None or state.data.get("_done"):
            print("\n  [DONE] Reached terminal state.")
            break

    _clean_exit = state.iteration < MAX_ITERATIONS
    if state.iteration >= MAX_ITERATIONS:
        print(f"\n  [STOPPED] Max iterations ({MAX_ITERATIONS}) reached.")
        _clean_exit = False

    if state.schema_violations > 0:
        print(f"\n  [SCHEMA] {state.schema_violations} total schema violation(s) during execution")
    dump_trace(iterations=state.iteration, clean_exit=_clean_exit)
    print(f"\nFinal state.data keys: {list(state.data.keys())}")
    return state


if __name__ == "__main__":
    run()