#!/usr/bin/env python3
"""
Plan and Solve — Generated by Agent Ontology Instantiation Engine
Spec: Plan-and-Solve agent that decomposes a problem into sub-problems, solves each with verification and retry logic, then synthesizes a final answer.
"""

import json
import os
import sys
import time
from datetime import datetime

# ═══════════════════════════════════════════════════════════
# Trace Log
# ═══════════════════════════════════════════════════════════

TRACE = []

def trace_call(agent_label, model, system_prompt, user_message, response, duration_ms):
    entry = {
        "timestamp": datetime.now().isoformat(),
        "agent": agent_label,
        "model": model,
        "system_prompt": system_prompt,
        "user_message": user_message,
        "response": response,
        "duration_ms": duration_ms,
    }
    TRACE.append(entry)
    print(f"    [{agent_label}] ({model}, {duration_ms}ms)")
    print(f"      IN:  {user_message[:300]}")
    print(f"      OUT: {response[:300]}")


def dump_trace(path="trace.json", iterations=0, clean_exit=True):
    # Compute metrics
    total_ms = sum(e["duration_ms"] for e in TRACE)
    agents_used = list(set(e["agent"] for e in TRACE))
    schema_ok = 0
    for e in TRACE:
        try:
            r = e["response"].strip()
            if r.startswith("```"): r = "\n".join(r.split("\n")[1:-1])
            json.loads(r if r.startswith("{") else r[r.find("{"):r.rfind("}")+1])
            schema_ok += 1
        except (json.JSONDecodeError, ValueError):
            pass
    est_input_tokens = sum(len(e.get("user_message",""))//4 for e in TRACE)
    est_output_tokens = sum(len(e.get("response",""))//4 for e in TRACE)
    metrics = {
        "total_llm_calls": len(TRACE),
        "total_duration_ms": total_ms,
        "avg_call_ms": total_ms // max(len(TRACE), 1),
        "iterations": iterations,
        "clean_exit": clean_exit,
        "agents_used": agents_used,
        "schema_compliance": f"{schema_ok}/{len(TRACE)}",
        "est_input_tokens": est_input_tokens,
        "est_output_tokens": est_output_tokens,
    }
    output = {"metrics": metrics, "trace": TRACE}
    with open(path, "w") as f:
        json.dump(output, f, indent=2)
    print(f"\nTrace written to {path} ({len(TRACE)} calls, {total_ms}ms total)")
    print(f"  Schema compliance: {schema_ok}/{len(TRACE)}, est tokens: ~{est_input_tokens}in/~{est_output_tokens}out")
    return metrics

# ═══════════════════════════════════════════════════════════
# LLM Call Infrastructure
# ═══════════════════════════════════════════════════════════

# Model override: set AGENT_ONTOLOGY_MODEL env var to override all agent models at runtime
_MODEL_OVERRIDE = os.environ.get("AGENT_ONTOLOGY_MODEL", "")
_OPENROUTER_API_KEY = os.environ.get("OPENROUTER_API_KEY", "")


def _openrouter_model_id(model):
    """Map spec model names to OpenRouter model IDs (provider/model format)."""
    if "/" in model:
        return model  # already in provider/model format
    if model.startswith("gemini"):
        return f"google/{model}"
    if model.startswith("claude") or model.startswith("anthropic"):
        return f"anthropic/{model}"
    if model.startswith("gpt") or model.startswith("o1") or model.startswith("o3"):
        return f"openai/{model}"
    return model  # pass through as-is


def _call_openrouter(model, system_prompt, user_message, temperature, max_tokens):
    from openai import OpenAI
    client = OpenAI(
        base_url="https://openrouter.ai/api/v1",
        api_key=_OPENROUTER_API_KEY,
    )
    response = client.chat.completions.create(
        model=_openrouter_model_id(model),
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_message},
        ],
        temperature=temperature,
        max_tokens=max_tokens,
    )
    return response.choices[0].message.content


def call_llm(model, system_prompt, user_message, temperature=0.7, max_tokens=4096, retries=3):
    if _MODEL_OVERRIDE:
        model = _MODEL_OVERRIDE
    for attempt in range(retries):
        try:
            if _OPENROUTER_API_KEY:
                return _call_openrouter(model, system_prompt, user_message, temperature, max_tokens)
            elif model.startswith("claude") or model.startswith("anthropic"):
                return _call_anthropic(model, system_prompt, user_message, temperature, max_tokens)
            elif model.startswith("gemini"):
                return _call_gemini(model, system_prompt, user_message, temperature, max_tokens)
            else:
                return _call_openai(model, system_prompt, user_message, temperature, max_tokens)
        except Exception as e:
            if attempt < retries - 1:
                wait = 2 ** attempt
                print(f"    [RETRY] {type(e).__name__}: {e} — retrying in {wait}s (attempt {attempt+1}/{retries})")
                import time as _time; _time.sleep(wait)
            else:
                print(f"    [FAIL] {type(e).__name__}: {e} after {retries} attempts")
                return json.dumps({"stub": True, "model": model, "error": str(e)})


def _call_openai(model, system_prompt, user_message, temperature, max_tokens):
    from openai import OpenAI
    client = OpenAI()
    response = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_message},
        ],
        temperature=temperature,
        max_tokens=max_tokens,
    )
    return response.choices[0].message.content


def _call_anthropic(model, system_prompt, user_message, temperature, max_tokens):
    import anthropic
    client = anthropic.Anthropic()
    response = client.messages.create(
        model=model,
        max_tokens=max_tokens,
        system=system_prompt,
        messages=[{"role": "user", "content": user_message}],
    )
    return response.content[0].text


def _call_gemini(model, system_prompt, user_message, temperature, max_tokens):
    from google import genai
    client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY", ""))
    response = client.models.generate_content(
        model=model,
        contents=f"{system_prompt}\n\n{user_message}",
        config={"temperature": temperature, "max_output_tokens": max_tokens},
    )
    return response.text

# ═══════════════════════════════════════════════════════════
# Schema Registry
# ═══════════════════════════════════════════════════════════

SCHEMAS = {
    "PlannerInput": {
        "description": """Input to the planner agent""",
        "fields": [{"name": "problem", "type": "string"}],
    },
    "Decomposition": {
        "description": """Output from the planner: a list of sub-problems""",
        "fields": [{"name": "sub_problems", "type": "list<SubProblem>"}],
    },
    "SubProblem": {
        "description": """A single sub-problem in the decomposition""",
        "fields": [{"name": "index", "type": "integer"}, {"name": "description", "type": "string"}, {"name": "depends_on", "type": "list<integer>"}],
    },
    "SolverInput": {
        "description": """Input to the solver agent""",
        "fields": [{"name": "problem", "type": "string"}, {"name": "sub_description", "type": "string"}, {"name": "prior_solutions", "type": "list<SubSolution>"}],
    },
    "SubSolution": {
        "description": """A solution to a single sub-problem""",
        "fields": [{"name": "solution_text", "type": "string"}, {"name": "confidence", "type": "integer"}],
    },
    "VerifierInput": {
        "description": """Input to the verifier agent""",
        "fields": [{"name": "problem", "type": "string"}, {"name": "sub_description", "type": "string"}, {"name": "solution_text", "type": "string"}],
    },
    "VerificationResult": {
        "description": """Output from the verifier""",
        "fields": [{"name": "is_valid", "type": "boolean"}, {"name": "issues", "type": "list<string>"}, {"name": "improvement_suggestions", "type": "list<string>"}],
    },
    "SynthesizerInput": {
        "description": """Input to the synthesizer agent""",
        "fields": [{"name": "problem", "type": "string"}, {"name": "solved_sub_solutions", "type": "list<SubSolution>"}],
    },
    "SynthesizedAnswer": {
        "description": """Final combined answer from the synthesizer""",
        "fields": [{"name": "final_answer", "type": "string"}, {"name": "synthesis_notes", "type": "string"}],
    },
}


def validate_output(data, schema_name):
    """Validate parsed LLM output against schema. Returns list of issues."""
    schema = SCHEMAS.get(schema_name)
    if not schema or "raw" in data:
        return []
    issues = []
    for field in schema["fields"]:
        fname = field["name"]
        ftype = field["type"]
        if fname not in data:
            issues.append(f"Missing field '{fname}' ({ftype})")
            continue
        val = data[fname]
        if ftype == "string" and not isinstance(val, str):
            issues.append(f"Field '{fname}' expected string, got {type(val).__name__}")
        elif ftype == "integer" and not isinstance(val, (int, float)):
            issues.append(f"Field '{fname}' expected integer, got {type(val).__name__}")
        elif ftype.startswith("list") and not isinstance(val, list):
            issues.append(f"Field '{fname}' expected list, got {type(val).__name__}")
        elif ftype.startswith("enum["):
            allowed = [v.strip() for v in ftype[5:-1].split(",")]
            if val not in allowed:
                issues.append(f"Field '{fname}' value '{val}' not in {allowed}")
    if issues:
        print(f"    [SCHEMA] {schema_name}: {len(issues)} issue(s): {issues[0]}")
    return issues


def build_input(state, schema_name):
    """Build an input dict for an agent call using schema field names.
    Pulls matching keys from state.data, checking both flat keys and
    values nested inside dict entries (e.g. state.data["xxx_input"]["field"])."""
    schema = SCHEMAS.get(schema_name)
    if not schema:
        return state.data
    result = {}
    for field in schema["fields"]:
        fname = field["name"]
        if fname in state.data:
            result[fname] = state.data[fname]
        else:
            # Search nested dicts in state.data for the field
            for _k, _v in state.data.items():
                if isinstance(_v, dict) and fname in _v:
                    result[fname] = _v[fname]
                    break
    return result


def output_instruction(schema_name):
    """Generate a JSON output instruction string for the LLM."""
    schema = SCHEMAS.get(schema_name)
    if not schema:
        return ""
    fields = ", ".join(f'"{f["name"]}": <{f["type"]}>' for f in schema["fields"])
    return f"\n\nRespond with ONLY valid JSON matching this schema: {{{fields}}}"


def parse_response(response, schema_name):
    """Parse an LLM response according to an output schema.
    Returns a dict of field values, or {"raw": response} if parsing fails."""
    import re as _re
    text = response.strip()
    # Handle markdown code blocks
    if text.startswith("```"):
        lines = text.split("\n")
        lines = lines[1:]  # skip ```json
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        text = "\n".join(lines)
    # Attempt 1: direct parse
    try:
        parsed = json.loads(text)
        if isinstance(parsed, dict):
            return parsed
        return {"value": parsed}
    except json.JSONDecodeError:
        pass
    # Attempt 2: extract JSON object from prose
    start = text.find("{")
    end = text.rfind("}") + 1
    if start >= 0 and end > start:
        candidate = text[start:end]
        try:
            return json.loads(candidate)
        except json.JSONDecodeError:
            pass
        # Attempt 3: fix trailing commas
        fixed = _re.sub(r",\s*}", "}", candidate)
        fixed = _re.sub(r",\s*]", "]", fixed)
        try:
            return json.loads(fixed)
        except json.JSONDecodeError:
            pass
        # Attempt 4: find matching braces (handle nested)
        depth = 0
        for i, ch in enumerate(text[start:], start):
            if ch == "{": depth += 1
            elif ch == "}": depth -= 1
            if depth == 0:
                try:
                    return json.loads(text[start:i+1])
                except json.JSONDecodeError:
                    break
    return {"raw": response}


# ═══════════════════════════════════════════════════════════
# Agent Wrappers
# ═══════════════════════════════════════════════════════════

def invoke_planner(user_message, output_schema=None):
    """Planner Agent"""
    system = """You are a planning agent. Given a complex problem, decompose it into a numbered list of
smaller, sequential sub-problems. Each sub-problem should be self-contained enough to solve
independently, but they should be ordered so later sub-problems can build on earlier solutions.
Output JSON with "sub_problems": a list of objects, each with "index" (integer starting at 1),
"description" (string), and "depends_on" (list of indices this sub-problem depends on, or empty).
"""
    if output_schema:
        system += output_instruction(output_schema)
    t0 = time.time()
    result = call_llm(
        model="gemini-3-flash-preview",
        system_prompt=system,
        user_message=user_message,
        temperature=0.7,
        max_tokens=4096,
    )
    trace_call("Planner Agent", "gemini-3-flash-preview", system, user_message, result, int((time.time()-t0)*1000))
    return result


def invoke_solver(user_message, output_schema=None):
    """Solver Agent"""
    system = """You are a problem-solving agent. Given a sub-problem description, the original problem for context,
and any previously solved sub-problem solutions, produce a solution. Output JSON with
"solution_text" (string with your solution) and "confidence" (integer 1-10).
"""
    if output_schema:
        system += output_instruction(output_schema)
    t0 = time.time()
    result = call_llm(
        model="gemini-3-flash-preview",
        system_prompt=system,
        user_message=user_message,
        temperature=0.7,
        max_tokens=4096,
    )
    trace_call("Solver Agent", "gemini-3-flash-preview", system, user_message, result, int((time.time()-t0)*1000))
    return result


def invoke_verifier(user_message, output_schema=None):
    """Verifier Agent"""
    system = """You are a verification agent. Given a sub-problem, its proposed solution, and the original problem,
check whether the solution is correct, complete, and consistent. Output JSON with "is_valid"
(boolean), "issues" (list of strings describing any problems found), and "suggestions" (list of
strings with improvement suggestions).
"""
    if output_schema:
        system += output_instruction(output_schema)
    t0 = time.time()
    result = call_llm(
        model="gemini-3-flash-preview",
        system_prompt=system,
        user_message=user_message,
        temperature=0.7,
        max_tokens=4096,
    )
    trace_call("Verifier Agent", "gemini-3-flash-preview", system, user_message, result, int((time.time()-t0)*1000))
    return result


def invoke_synthesizer(user_message, output_schema=None):
    """Synthesizer Agent"""
    system = """You are a synthesis agent. Given the original problem and all verified sub-solutions,
combine them into a single coherent final answer. Ensure consistency across sub-solutions
and present a unified response. Output JSON with "final_answer" (string) and
"synthesis_notes" (string describing how sub-solutions were combined).
"""
    if output_schema:
        system += output_instruction(output_schema)
    t0 = time.time()
    result = call_llm(
        model="gemini-3-flash-preview",
        system_prompt=system,
        user_message=user_message,
        temperature=0.7,
        max_tokens=4096,
    )
    trace_call("Synthesizer Agent", "gemini-3-flash-preview", system, user_message, result, int((time.time()-t0)*1000))
    return result



# ═══════════════════════════════════════════════════════════
# Agent State
# ═══════════════════════════════════════════════════════════

class AgentState:
    """Runtime state for Plan and Solve"""
    def __init__(self):
        self.data = {}  # current data flowing through the pipeline
        self.iteration = 0
        self.schema_violations = 0


# ═══════════════════════════════════════════════════════════
# Process Functions
# ═══════════════════════════════════════════════════════════

def process_receive_problem(state):
    """
    Receive Problem
    Accept the complex problem and initialize state
    """
    print(f"  → Receive Problem")

    # Logic from spec
    state.data["solved_sub_solutions"] = []
    state.data["current_sub_index"] = 0
    state.data["retry_count"] = 0
    state.data["max_retries"] = 2
    print(f"    Problem: {state.data.get('problem', '')[:100]}")
    if state.data.get("_done"):
        return state

    return state


def process_decompose(state):
    """
    Decompose Problem
    Invoke the planner agent to break the problem into sub-problems
    """
    print(f"  → Decompose Problem")

    # Logic from spec
    print(f"    Decomposing problem into sub-problems...")
    if state.data.get("_done"):
        return state

    # Flatten nested dicts: promote schema fields to top-level state.data
    for _nested_val in list(state.data.values()):
        if isinstance(_nested_val, dict):
            for _nk, _nv in _nested_val.items():
                if _nk not in state.data:
                    state.data[_nk] = _nv

    # Invoke: Decompose into sub-problems
    planner_input = build_input(state, "PlannerInput")
    planner_msg = json.dumps(planner_input, default=str)
    planner_raw = invoke_planner(planner_msg, output_schema="Decomposition")
    planner_result = parse_response(planner_raw, "Decomposition")
    # Validate and merge output fields into state.data
    state.schema_violations += len(validate_output(planner_result, "Decomposition"))
    state.data.update(planner_result)
    state.data["decomposition"] = planner_result
    state.data["decompose_result"] = planner_result
    print(f"    ← Planner Agent: {planner_result}")

    return state


def process_solve_subproblem(state):
    """
    Solve Sub-problem
    Invoke the solver agent on the current sub-problem
    """
    print(f"  → Solve Sub-problem")

    # Logic from spec
    sub_problems = state.data.get("sub_problems", [])
    idx = state.data.get("current_sub_index", 0)
    if idx < len(sub_problems):
        current = sub_problems[idx]
        state.data["current_sub_description"] = current.get("description", "")
        print(f"    Solving sub-problem {idx + 1}/{len(sub_problems)}: {current.get('description', '')[:80]}")
    else:
        print(f"    No more sub-problems to solve")
    if state.data.get("_done"):
        return state

    # Flatten nested dicts: promote schema fields to top-level state.data
    for _nested_val in list(state.data.values()):
        if isinstance(_nested_val, dict):
            for _nk, _nv in _nested_val.items():
                if _nk not in state.data:
                    state.data[_nk] = _nv

    # Invoke: Solve current sub-problem
    solver_input = build_input(state, "SolverInput")
    solver_msg = json.dumps(solver_input, default=str)
    solver_raw = invoke_solver(solver_msg, output_schema="SubSolution")
    solver_result = parse_response(solver_raw, "SubSolution")
    # Validate and merge output fields into state.data
    state.schema_violations += len(validate_output(solver_result, "SubSolution"))
    state.data.update(solver_result)
    state.data["sub_solution"] = solver_result
    state.data["solve_subproblem_result"] = solver_result
    print(f"    ← Solver Agent: {solver_result}")

    return state


def process_verify_solution(state):
    """
    Solution valid?
    """
    print(f"  → Solution valid?")

    # Gate: is_valid == True
    # Branch: valid → accept_solution
    # Branch: invalid → retry_or_next

    if state.data.get("is_valid") == True:
        print(f"    → valid")
        return "accept_solution"
    else:
        print(f"    → invalid")
        return "retry_or_next"


def process_accept_solution(state):
    """
    Accept Solution
    Record the verified sub-solution and advance to the next sub-problem
    """
    print(f"  → Accept Solution")

    # Logic from spec
    solution = {
        "index": state.data.get("current_sub_index", 0),
        "description": state.data.get("current_sub_description", ""),
        "solution_text": state.data.get("solution_text", ""),
        "confidence": state.data.get("confidence", 0),
    }
    solved = state.data.get("solved_sub_solutions", [])
    solved.append(solution)
    state.data["solved_sub_solutions"] = solved
    state.data["current_sub_index"] = state.data.get("current_sub_index", 0) + 1
    state.data["retry_count"] = 0
    print(f"    Accepted solution for sub-problem {solution['index'] + 1}")
    if state.data.get("_done"):
        return state

    return state


def process_retry_or_next(state):
    """
    Retries left?
    """
    print(f"  → Retries left?")

    # Gate: retry_count < max_retries
    # Branch: retries remaining → solve_subproblem
    # Branch: retries exhausted → accept_solution

    if (state.data.get("retry_count", 0)) < (state.data.get("max_retries", 0)):
        print(f"    → retries remaining")
        return "solve_subproblem"
    else:
        print(f"    → retries exhausted")
        return "accept_solution"


def process_check_remaining(state):
    """
    More sub-problems?
    """
    print(f"  → More sub-problems?")

    # Gate: current_sub_index < total_sub_problems
    # Branch: more sub-problems → solve_subproblem
    # Branch: all solved → synthesize

    if (state.data.get("current_sub_index", 0)) < (state.data.get("total_sub_problems", 0)):
        print(f"    → more sub-problems")
        return "solve_subproblem"
    else:
        print(f"    → all solved")
        return "synthesize"


def process_invoke_verifier(state):
    """
    Invoke Verifier
    Send the current sub-solution to the verifier agent for checking
    """
    print(f"  → Invoke Verifier")

    # Logic from spec
    state.data["retry_count"] = state.data.get("retry_count", 0) + 1
    print(f"    Verifying sub-problem {state.data.get('current_sub_index', 0) + 1} (attempt {state.data['retry_count']})")
    if state.data.get("_done"):
        return state

    # Flatten nested dicts: promote schema fields to top-level state.data
    for _nested_val in list(state.data.values()):
        if isinstance(_nested_val, dict):
            for _nk, _nv in _nested_val.items():
                if _nk not in state.data:
                    state.data[_nk] = _nv

    # Invoke: Check solution
    verifier_input = build_input(state, "VerifierInput")
    verifier_msg = json.dumps(verifier_input, default=str)
    verifier_raw = invoke_verifier(verifier_msg, output_schema="VerificationResult")
    verifier_result = parse_response(verifier_raw, "VerificationResult")
    # Validate and merge output fields into state.data
    state.schema_violations += len(validate_output(verifier_result, "VerificationResult"))
    state.data.update(verifier_result)
    state.data["verification_result"] = verifier_result
    state.data["invoke_verifier_result"] = verifier_result
    print(f"    ← Verifier Agent: {verifier_result}")

    return state


def process_synthesize(state):
    """
    Synthesize
    Invoke the synthesizer agent to combine all sub-solutions into a final answer
    """
    print(f"  → Synthesize")

    # Logic from spec
    solved = state.data.get("solved_sub_solutions", [])
    print(f"    Synthesizing {len(solved)} sub-solutions into final answer")
    state.data["_done"] = True
    if state.data.get("_done"):
        return state

    # Flatten nested dicts: promote schema fields to top-level state.data
    for _nested_val in list(state.data.values()):
        if isinstance(_nested_val, dict):
            for _nk, _nv in _nested_val.items():
                if _nk not in state.data:
                    state.data[_nk] = _nv

    # Invoke: Combine sub-solutions
    synthesizer_input = build_input(state, "SynthesizerInput")
    synthesizer_msg = json.dumps(synthesizer_input, default=str)
    synthesizer_raw = invoke_synthesizer(synthesizer_msg, output_schema="SynthesizedAnswer")
    synthesizer_result = parse_response(synthesizer_raw, "SynthesizedAnswer")
    # Validate and merge output fields into state.data
    state.schema_violations += len(validate_output(synthesizer_result, "SynthesizedAnswer"))
    state.data.update(synthesizer_result)
    state.data["synthesized_answer"] = synthesizer_result
    state.data["synthesize_result"] = synthesizer_result
    print(f"    ← Synthesizer Agent: {synthesizer_result}")

    return state


# ═══════════════════════════════════════════════════════════
# State Machine Executor
# ═══════════════════════════════════════════════════════════

PROCESSES = {
    "receive_problem": process_receive_problem,
    "decompose": process_decompose,
    "solve_subproblem": process_solve_subproblem,
    "verify_solution": process_verify_solution,
    "accept_solution": process_accept_solution,
    "retry_or_next": process_retry_or_next,
    "check_remaining": process_check_remaining,
    "invoke_verifier": process_invoke_verifier,
    "synthesize": process_synthesize,
}

TRANSITIONS = {
    "receive_problem": "decompose",
    "decompose": "solve_subproblem",
    "solve_subproblem": "invoke_verifier",
    # "verify_solution": determined by gate logic
    "accept_solution": "check_remaining",
    # "retry_or_next": determined by gate logic
    # "check_remaining": determined by gate logic
    "invoke_verifier": "verify_solution",
    "synthesize": None,  # terminal
}


MAX_ITERATIONS = int(os.environ.get("AGENT_ONTOLOGY_MAX_ITER", "100"))


def run(initial_data=None):
    """Plan and Solve — main execution loop"""
    state = AgentState()
    if initial_data:
        state.data.update(initial_data)

    current = "receive_problem"
    print(f"\n════════════════════════════════════════════════════════════")
    print(f"  Plan and Solve")
    print(f"  Plan-and-Solve agent that decomposes a problem into sub-problems, solves each with verification and retry logic, then synthesizes a final answer.")
    print(f"════════════════════════════════════════════════════════════\n")

    while current and state.iteration < MAX_ITERATIONS:
        state.iteration += 1
        print(f"\n[Iteration {state.iteration}] State: {current}")

        process_fn = PROCESSES.get(current)
        if not process_fn:
            print(f"  Unknown process: {current}")
            break

        result = process_fn(state)

        if current in ['verify_solution', 'retry_or_next', 'check_remaining']:
            current = result
        else:
            current = TRANSITIONS.get(current)

        # Fan-out: if transition is a list, run all branches sequentially
        while isinstance(current, list):
            _targets = current
            for _ft in _targets:
                state.iteration += 1
                print(f"\n[Iteration {state.iteration}] State: {_ft} (fan-out)")
                _fn = PROCESSES.get(_ft)
                if _fn:
                    _fn(state)
            # Collect unique next-hops from all fan-out targets
            _next_set = []
            for _ft in _targets:
                _nt = TRANSITIONS.get(_ft)
                if _nt is not None and _nt not in _next_set:
                    _next_set.append(_nt)
            current = _next_set[0] if len(_next_set) == 1 else (_next_set if _next_set else None)

        if current is None or state.data.get("_done"):
            print("\n  [DONE] Reached terminal state.")
            break

    _clean_exit = state.iteration < MAX_ITERATIONS
    if state.iteration >= MAX_ITERATIONS:
        print(f"\n  [STOPPED] Max iterations ({MAX_ITERATIONS}) reached.")
        _clean_exit = False

    if state.schema_violations > 0:
        print(f"\n  [SCHEMA] {state.schema_violations} total schema violation(s) during execution")
    dump_trace(iterations=state.iteration, clean_exit=_clean_exit)
    print(f"\nFinal state.data keys: {list(state.data.keys())}")
    return state


if __name__ == "__main__":
    run()